### ISSUE TITLE
Sourcemaps for code compiled under WSL

### ISSUE THREAD

**Issue by bmayen** [Microsoft/vscode-chrome-debug#524] opened 2017-10-07 00:38 UTC
- VS Code Version:
1.17

Not sure if this is a bug or user error on my part.

I'm using Windows 10 with WSL. My source code lives under `C:\Users\b\work\fooApp`. It is build with Webpack (Angular-CLI) via WSL, which sees the code under `/mnt/c/Users/b/work/fooApp`.

When I attempt to debug this app via VSCode, sourcemaps are not found. Chrome debugger works fine and the Sources tab shows them under `webpack:////mnt/c/Users/b/work/fooApp`.

`.scripts` outputs lines like the following:
```
› http://localhost:4200/auth.module.chunk.js
    - webpack:\mnt\c\Users\b\work\fooApp\src\app\features\auth\auth.module.ts (/mnt/c/Users/b/work/fooApp/src/app/features/auth/auth.module.ts)
```

I've tried adding "sourceMapPathOverrides" to point `/mnt/c/` to `C:\` but get the exact same output from `.scripts`.

Any thoughts on how to make this work? Is this a supported use case?

**Comment by roblourens** [comment] 2017-10-07 04:31
Ah, yeah the node debugger expects paths in a different format from the current system, but chrome-debug hasn't needed that yet.

Can you try `sourceMapPathOverrides` with `"webpack:////mnt/c/": "C:\"`?

**Comment by bmayen** [comment] 2017-10-07 12:18
Thanks @roblourens. Yes, have tried that as well. The following trace info was done using this config:
```
    {
      "type": "chrome",
      "request": "attach",
      "name": "Attach to Chrome on localhost",
      "port": 9222,
      "url": "http://localhost:4200/*",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:////mnt/c/": "C:/"
      },
      "trace": "verbose"
    }
```
Have tried with many permutations of that sourceMapPathOverrrides actually. Copying in the default overrides from the plugin, adding wildcards to `/mnt/c/`, etc. All see to produce the same output in `.scripts`

Here's some addition info from verbose trace. The resolved sourceRoot looks strange to me, but I'm not well-versed in how this should work. 
*Side note*: For NDA reasons I have to change the urls I'm pasting in here. Going to abbreviate them a bit more from now on to make it a little easier ;)
```
SourceMap: webRoot: c:\Users\...\fooApp
SourceMap: resolved sourceRoot webpack:/// -> c:\Users\...\fooApp\webpack:\
SourceMaps.scriptParsed: http://localhost:4200/auth.module.chunk.js was just loaded and has mapped sources: ["/mnt/c/Users/.../fooApp/src/app/features/auth/auth.module.ts"
```

There are also entries like the following:
```
SourceMaps.getMapForGeneratedPath: Using inlined sourcemap in ng:///AuthModule/ForgotPasswordComponent.ngfactory.js
SourceMap: creating for ng:///AuthModule/ForgotPasswordComponent.ngfactory.js
SourceMap: sourceRoot: 
SourceMap: sources: ["ng:///AuthModule/ForgotPasswordComponent.ngfactory.js","ng:///AuthModule/ForgotPasswordComponent.html"]
SourceMap: webRoot: c:\Users\brett\Work\etventure\claas\connect\fe
SourceMap: no sourceRoot specified, using webRoot + script path dirname: c:\Users\...\fooApp\AuthModule
SourceMaps.scriptParsed: ng:///AuthModule/ForgotPasswordComponent.ngfactory.js was just loaded and has mapped sources: ["c:\\Users\\...\\fooApp\\AuthModule\\ng:\\AuthModule\\ForgotPasswordComponent.ngfactory.js","c:\\Users\\...\\fooApp\\AuthModule\\ng:\\AuthModule\\ForgotPasswordComponent.html"]
```

I should also note that I'm using the latest version of the extension.

**Comment by roblourens** [comment] 2017-10-07 21:42
Thanks for the logs. It's probably time for me to bite the bullet, set up WSL and try this myself.

**Comment by bmayen** [comment] 2017-10-08 00:09
While this functionality would be hugely convenient, ultimately it's a nice-to-have for me. So if there isn't high demand for it, and if you have other high priority issues to address, no urgency from my side. Regardless, let me know if there's anything I can do to help whenever you do get to it!

**Comment by bmayen** [comment] 2017-10-27 11:45
@roblourens, now that this Chrome issue has been fixed (https://bugs.chromium.org/p/chromium/issues/detail?id=129539#c74) having this issue addressed would be really nice :) Makes IDE debugging much more attractive now that we can attach to an instance with developer tools already open.

**Comment by lightrow** [comment] 2018-01-19 20:31
i managed to get it working

`{
      "type": "chrome",
      "request": "attach",
      "name": "Attach to Chrome WSL",
      "port": 9222,
      "webRoot": "${workspaceFolder}",
      "url": "http://localhost:3000/",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "/mnt/c/Users/Jo/dev/node_app/*": "${workspaceFolder}/*"
      }`

you have to restart vscode after saving "launch.json" in order for sourcemap override to work. Why? No goddam clue, but it can easily be tested and reproduced.

took me a while to "figure" it out.

**Comment by bmayen** [comment] 2018-01-19 20:33
Thanks! Out of town for a week, but will try this out once I'm back!

**Comment by roblourens** [comment] 2018-01-19 22:32
> you have to restart vscode after saving "launch.json" in order for sourcemap override to work. Why? 

That shouldn't be the case... will investigate

**Comment by lightrow** [comment] 2018-01-20 20:32
not wsl-related, but linux version of vscode seems to apply sourcemaps instantly ( mapping from docker container )

i dont have access to that windows machine anymore, so perhaps it was my imagination after all... Maybe just making sure the paths were set precisely, down to every single slash, was what made it work.

**Comment by FiveOFive** [comment] 2018-02-01 22:51
Worked for me and I didn't need to restart VSCode after changing the launch config (v1.19.3 on Windows 10) . 
`
"sourceMapPathOverrides": {
                "/mnt/c/*": "C:\\*"
            }
`

It was a bit difficult to find what is needed in a launch config for WSL, since at least some of the official documentation does not mention the sourceMapPathOverrides attribute. I was following [https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes](url). It would be helpful to have it documented there.

**Comment by Jule-** [comment] 2018-02-24 06:04
There is something strange in the VS Code behavior...

I guess compiling and serving with WSL is generating sourcemaps with pattern `/mnt/[drive]/` while running VS Code under Windows makes him working with file paths pattern `[drive]:\`. As a result, remote debugging is expecting sourcemaps in `[drive]:\` and cannot match sources with sourcemaps paths in VS Code. This is why **setting only `sourceMapPathOverrides` does the trick**.

But what I don't understand is where `localRoot` and `remoteRoot` take place since it seems they are designed for this specific purpose, cf. doc: [VS Code - Remote debugging](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_remote-debugging)

> By default, VS Code will stream the debugged source from the remote Node.js folder to the local VS Code and show it in a read-only editor. You can step through this code, but cannot modify it. If you want VS Code to open the editable source from your workspace instead, you can setup a mapping between the remote and local locations. A `localRoot` and a `remoteRoot` attribute can be used to map paths between a local VS Code project and a (remote) Node.js folder. This works even locally on the same system or across different operating systems. Whenever a code path needs to be converted from the remote Node.js folder to a local VS Code path, the `remoteRoot` path is stripped off the path and replaced by `localRoot`. For the reverse conversion, the `localRoot` path is replaced by the `remoteRoot`.

While they are not working for me, at least on a WSL remote configuration.

Looking at traces, when trying to set `localRoot` and `remoteRoot`, this one seems to be the root issue:
```
SourceMaps.scriptParsed: f:\project\hello.js was just loaded and has mapped sources: ["c:\\mnt\\f\\project\\hello.js"]
```
Strange `c:\\mnt\\f\\` path generation... But later in traces:
```
Mapped localToRemote: f:\project\hello.js -> /mnt/f/project/hello.js
```
All seems finally OK! Except that:
```
SourceMaps.setBP: SourceMaps are enabled but f:\project\hello.js is a runtime script
```
(I don't know what it means and why it happens...)
And then no nominal breakpoint creation.

For example if I correctly set `sourceMapPathOverrides` I get:
```
SourceMaps.setBP: Mapped f:\project\hello.js to /mnt/f/project/hello.js
SourceMaps.setBP: Mapped f:\project\hello.js:60:1 to /mnt/f/project/hello.js:87:1
→ To target: "{\"id\":10,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"1658\",\"lineNumber\":86,\"columnNumber\":0},\"end\":{\"scriptId\":\"1658\",\"lineNumber\":87,\"columnNumber\":0},\"restrictToFunction\":false}}"
← From target: {"id":10,"result":{"locations":[{"scriptId":"1658","lineNumber":86,"columnNumber":18},{"scriptId":"1658","lineNumber":86,"columnNumber":43,"type":"call"}]}}
→ To target: "{\"id\":11,\"method\":\"Debugger.setBreakpointByUrl\",\"params\":{\"urlRegex\":\"\\\\/mnt\\\\/project\\\\/hello\\\\.js\",\"lineNumber\":86,\"columnNumber\":18}}"
← From target: {"id":11,"result":{"breakpointId":"/\\/mnt\\/f\\/project\\/hello\\.js/:86:18","locations":[{"scriptId":"1658","lineNumber":86,"columnNumber":18}]}}
SourceMaps.setBP: Mapped /mnt/f/project/hello.js:87:19 to f:\project\hello.js:60
```

This is why I think there is a real issue there.

---

IMHO, since `launch.json` is intended to be committed and every developer could use its favorite drive, it should be better to introduce a VS Code launch task parameter which could tell VS Code to use sourcemap path conversion for WSL (maybe something like `sourceMapPathWSL` or allow a new `WSL` option for `sourceMapPathOverrides`). I think a little regex can do the trick.
Or even automatically detect WSL paths on fail and activate intended path conversion for the session.

HTH finding a fix!

**Comment by bmayen** [comment] 2018-04-05 21:31
Still can't get this to work. Have tried every combination I can think of but still get "breakpoint ignored because generated code not found". Using Webpack 4 via Angular CLI. Anybody else with this setup having any luck?

**Comment by ariofrio** [comment] 2018-09-21 01:09
For reference, this is what I'm using with create-react-app to get breakpoints to work using WSL:

```
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:3001",
      "webRoot": "${workspaceFolder}/src",
      "sourceMapPathOverrides": {
        "top/localhost:3001/mnt/c/*": "C:/*",
        "/mnt/c/*": "C:/*",
        "file://mnt/c/*": "C:/*",
        "webpack:///src/*": "${webRoot}/*"
      },
    }
```

I just added all the combinations I could think of, and I'm not sure which one(s) is doing the trick. Not using WSL anymore for this project because of other issues, so I'm not able to further investigate right now.

**Comment by roblourens** [comment] 2018-09-21 01:19
Handling this with `sourceMapPathOverrides` is the right answer. You can debug with the `.scripts` command and apply `pathMappings` or `sourceMapPathOverrides` as needed.  I am going to close this because it needs to be handled case-by-case, it's not a general issue.

**Closed by roblourens** 2018-09-21 01:19 UTC
