### ISSUE TITLE
Angular 2 debugging is broken after updating vscode-chrome-debug to version1.1.0

### ISSUE THREAD

**Issue by herb-stone** [Microsoft/vscode-chrome-debug#256] opened 2016-10-13 07:42 UTC
My project is based on https://github.com/preboot/angular2-webpack. Starting the debugging I found the following error multiple times (>50 times in a row): 

```
SourceMaps.getMapForGeneratedPath: exception while processing sourcemap: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at Object.getComputedSourceRoot (C:\Users\H\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapUtils.js:50:40)
    at new SourceMap (C:\Users\H\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:30:51)
    at sourceMapContentsP.then.e (C:\Users\H\.vscode\extensions\msjsdiag.debugger-for-chrome-1.1.0\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:39:24)
```
If seems that the error is handled in this try catch block:

```
            try {
                // In MS Edge this throws
XXX             fetchPromise = global['fetch']();
            }
            catch (e) {
                // In Chrome this throws instead.
                fetchPromise = global['fetch']('about:blank');
            }
            // ignore output to prevent error;

```

**Comment by auchenberg** [comment] 2016-10-13 17:58
Might be caused by a missing source map path? Looks like our source mapping engine should handle this case

**Comment by roblourens** [comment] 2016-10-14 02:23
I actually can repro this one - there is a case where the path for the sourcemap for an eval script that can't be resolved to a script on disk is not handled carefully enough. Thanks for the report.

**Comment by roblourens** [comment] 2016-10-14 05:35
Should be fixed in 1.2.0

**Closed by roblourens** 2016-10-14 05:35 UTC
Labels: bug

**Comment by leotm** [comment] 2016-12-01 20:15
Being taken to the try catch block each time now, without any errors.

Just spotted this too: https://stackoverflow.com/questions/40913200/angular2-how-to-prevent-exception-on-globalfetch-in-zone-js

On v2.3.2

**Comment by roblourens** [comment] 2016-12-01 21:46
All I can suggest is, run with 'break on exceptions' disabled? Or you could add the name of that file to the `"experimentalSkipFiles"` list in your launch config. Or ask angular devs to not gratuitously throw exceptions. :)

**Comment by hlesesne** [comment] 2016-12-22 12:42
Just out of curiosity - does the skipFiles or experimentalSkipFiles solution work for anyone? I've added ["zone.js"], but it continues to pause on that same location.

**Comment by roblourens** [comment] 2016-12-22 17:54
What's the full path if you hover over the name of that file?

**Comment by hlesesne** [comment] 2016-12-22 20:59
I believe it was 1002/zone.js

I actually have it working with the excusion of only this:

"skipFiles": ["main.bundle.js"]

There are likely some unintended consequences to this, but my breakpoints are still being hit without the error in zone.js.

**Comment by roblourens** [comment] 2016-12-22 23:06
That implies that zone.js is included in your bundle and eval()ed, which makes it difficult to skip without skipping the whole file like you've done. When you skip a file by its actual name like main.bundle.js, you can tell Chrome to blackbox it before it's loaded. But when you use a name from the sourcemap like zone.js, we can't skip it until it's already loaded, and we've processed the sourcemap and everything, and it might hit an exception before then. You'll see the exact same behavior in Chrome devtools.

The only downside of your workaround is that you may miss exceptions or debugger statements in your own code.

**Comment by hlesesne** [comment] 2016-12-27 14:38
Thanks @roblourens. I did notice that I am missing exception in my own code, so I went ahead and added two launch configurations (one excluding the main.bundle.js and the other not), to quickly toggle between exception handling or not.

**Comment by subatomicglue** [comment] 2017-07-17 21:42
Any update when this will be fixed?   Really annoying having to hit > (resume debugger), and CTRL-W (close) the `zone.js` file everytime I restart the app in Chrome, which can be a few times a minute, 1000's of times a day - it _really_ breaks my flow.   And I dont want to disable Uncaught Exceptions... since....  well..... I want to catch them in __my__ code.    

`skipFiles` doesnt work:

```
{
  "name": "Launch Chrome - AVIA Connect Frontend (dev)",
  "runtimeArgs": ["--remote-debugging-port=9222"],
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:4200/",
  "port": 9222,
  "sourceMaps": true,
  "webRoot": "${workspaceRoot}/front/src",
  "trace": true,
  "userDataDir": "${workspaceRoot}/.vscode/chrome",
  "sourceMapPathOverrides": {
      "webpack:///*": "${workspaceRoot}/front/*"
  },
  "skipFiles":["zone.js", "polyfills.bundle.js", "node_modules/**/*.js", "lib/**/*.js", "build/polyfills.js"],
  "experimentalSkipFiles":["zone.js", "polyfills.bundle.js", "node_modules/**/*.js", "lib/**/*.js", "build/polyfills.js"]
},
```

I noticed that the breakpoint in `zone.js` doesn't happen when first launching chrome via `vscode`, but everytime I resave some source file, or restart (recycle icon) using vscode debugger, or hit reloadpage in chrome, then the breakpoint is hit. 


Any solution?

**Comment by roblourens** [comment] 2017-07-17 21:50
I don't have any other solution, there's probably no way around it in chrome devtools either, right?

**Comment by roblourens** [comment] 2017-07-17 21:51
Maybe smartStep would help, if all the code that you care about is sourcemapped.

**Comment by subatomicglue** [comment] 2017-07-17 21:58
I added `smartStep: true` to the config I posted above, but no change

breaks here in `zone.js`:
```
try {
                // In MS Edge this throws
                fetchPromise = global['fetch']();         <---------
            }
            catch (e) {
                // In Chrome this throws instead.
                fetchPromise = global['fetch']('about:blank');
            }
```

with this exception:
```
TypeError: Failed to execute 'fetch' on 'Window': 1 argument required, but only 0 present.
    at http://localhost:4200/polyfills.bundle.js:6624:47
    at http://localhost:4200/polyfills.bundle.js:6787:3
    at webpackJsonp.1541.Zone.assertZonePatched (http://localhost:4200/polyfills.bundle.js:6005:13)
    at Object.<anonymous> (http://localhost:4200/polyfills.bundle.js:6008:2)
    at Object.1541 (http://localhost:4200/polyfills.bundle.js:7611:30)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.711 (http://localhost:4200/polyfills.bundle.js:9794:77)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
    at Object.1544 (http://localhost:4200/polyfills.bundle.js:7625:18)
    at __webpack_require__ (http://localhost:4200/inline.bundle.js:53:30)
```

**Comment by subatomicglue** [comment] 2017-07-17 22:08
Also no change when I blackbox `zone.js` in chrome (since I'm using `angular-cli`, it's probably not an actual file, but bundled in some other).

**Comment by roblourens** [comment] 2017-07-17 22:11
Right, it's eval()d code.

**Comment by subatomicglue** [comment] 2017-07-17 22:12
Dumb (or excellent?) question, but who writes `zone.js`, and why do they want it to break there?

**Comment by roblourens** [comment] 2017-07-17 22:16
I think it's part of angular, and they seem to be testing `fetch` support for the browser.
