### ISSUE TITLE
ghost breakpoints on restart

### ISSUE THREAD

**Issue by Spown** [microsoft/vscode-chrome-debug#785] opened 2019-03-03 05:26 UTC
- VS Code Version: 1.31.1
- Log file: https://drive.google.com/uc?id=16hqvY62mdCjCagLknYukMQFTIrJcwa9x

>Breakpoints not working?

No, they work far too good even beyond the grave. I've been having this issue for years now, but it was relatively hard to pinpoint so I was hoping it will go away some day... I'm too lazy.

Steps to reproduce:

1. set a breakpoint and start the debugging session (order doesn't matter)
2. Initiate an action to hit the breakpoint
3. make simple change to the file, that doesn't move the breakpoint, for example add and then delete a new line somewhere before the point (which shows that if the content stays exactly the same it will still happen)
4. restart the session (via restart, not via stop&start) which will resave the files and refresh the page (so it is probably not the same usual "break-on-load" issue)
5. remove the breakpoint (repro on removing from left editor column and Breakpoints section and Remove All Breakpoints)
6. Initiate the action from 2.

This should hit the now non-existant breakpoint. Every restart will hit it again. Significant file change prior the subsequent restart may mend the issue. Introducing significant changes in 3. (first restart) usually won't help, even worse, it can move the point to a random position.

It may have something to do with deferring since all of my code is wrapped in ``$(function() { ... })`` i.e. it executes on page ready.

Thank you.

**Comment by Spown** [comment] 2019-08-07 16:06
still there, still annoying as hell...

**Comment by roblourens** [comment] 2019-08-16 22:11
Sorry for the slow response. I think I vaguely see what is happening in the script. It's related to keeping a breakpoint across a page refresh or navigation, and we try to reset the breakpoint after the refresh but shouldn't in this case. Then it is in a bad state and fails to remove the breakpoint when you remove it.

We are working on a larger change which should eliminate some issues like this. It's early but if you would like to try it out, you could install the nightly version of this extension: https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome-nightly and me know whether it helps.

**Comment by rori4** [comment] 2019-08-20 08:26
@roblourens I can confirm that I had the same problem and the debugger for chrome nightly solved it.  Thanks!

**Comment by Spown** [comment] 2019-08-20 09:01
yeah, I tried nightly on Insiders and at least with in OP mentioned steps it seems to be working fine.

**Comment by roblourens** [comment] 2019-08-21 01:04
Cool! @digeff

**Comment by Spown** [comment] 2020-02-17 11:46
happens again

**Comment by roblourens** [comment] 2020-02-17 18:19
So we are working towards a new debugger implementation (again, this is different even from the new version I mentioned earlier) I think this will likely be fixed there, would appreciate you trying it: https://code.visualstudio.com/updates/v1_42#_new-javascript-debugger

**Comment by fgallardograzio** [comment] 2020-10-24 03:25
@roblourens I've been using the new javascript debugger on vscode insiders for several months, and I've always experienced this issue.
It looks like after a file change the "real" breakpoints' position is not updated, so the next time it'll break in the lines in which the breakpoints used to be, not the ones in which they're now.

The indicators in vscode (the red dots next to the line numbers) do track the changes correctly and are shown in the correct lines, though.

This can be fixed by simply disabling / re-enabling all breakpoints.

**Comment by roblourens** [comment] 2020-10-26 18:19
@fgallardograzio could you open an issue in https://github.com/microsoft/vscode-js-debug/issues with a log?

**Comment by connor4312** [comment] 2020-11-03 19:43
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).

**Closed by connor4312** 2020-11-03 19:43 UTC
Labels: bug
