### ISSUE TITLE
Cannot connect to runtime process. Can't find a valid target that matches: about:blank

### ISSUE THREAD

**Issue by Godrules500** [microsoft/vscode-chrome-debug#871] opened 2019-07-02 14:45 UTC
I have made 0 changes, but yesterday when I was debugging it worked. Installed jest on another project (unrelated but figured I would add it) signed in this morning and now I cannot run it without the error in the title (screenshot below)

- VS Code Version: 1.35.1 and insiders version: 1.36-0
- Chrome Debugger Version:  4.11.6
- Log file (set `"trace": true` in launch config):

[vscode-chrome-debug.txt](https://github.com/microsoft/vscode-chrome-debug/files/3350636/vscode-chrome-debug.txt)

Steps to reproduce:

1. Open VSCode
2. Click Run

launch.json
    {
      "name": "ng serve",
      "type": "chrome",
      "request": "launch",
      "preLaunchTask": "npm: start",
      "url": "http://localhost:4200/#",
      "webRoot": "${workspaceFolder}"
    },

tasks.json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "start",
      "isBackground": true,
      "presentation": {
        "focus": true,
        "panel": "dedicated"
      },
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "problemMatcher": {
        "owner": "typescript",
        "source": "ts",
        "applyTo": "closedDocuments",
        "fileLocation": [
          "relative",
          "${cwd}"
        ],
        "pattern": "$tsc",
        "background": {
          "activeOnStart": true,
          "beginsPattern": {
            "regexp": "(.*?)"
          },
          "endsPattern": {
            "regexp": "Compiled |Failed to compile."
          }
        }
      }
    },
  ]
}

![image](https://user-images.githubusercontent.com/318063/60521769-d3ec4080-9cb5-11e9-89c2-05e18db8065f.png)

**Comment by roblourens** [comment] 2019-07-02 17:18
You might have another instance of chrome open in the background, maybe as a stuck process. Try closing all chrome instances or killing the processes. Or, try setting `port` to some random number in your launch config to make sure you get a new chrome instance/profile.

**Comment by Godrules500** [comment] 2019-07-02 18:41
I have tried a few things and receive the same error.
1) Restarted - **Failed**
2) Closed all instances of chrome via task manager - **Failed**
3) Changed Port Number to the below : **Failed**
      "url": "http://localhost:4300/#", and 
      "url": "http://localhost:4040/#"
4) Closed all Node services running in background: **Failed**

**Comment by roblourens** [comment] 2019-07-02 23:34
No I mean the `port` property in your launch config. Not the port of your server.

What is `localhost:9876`? Clearly you have a Chrome instance open somewhere to that url.

**Comment by Godrules500** [comment] 2019-07-03 12:26
I may not quite understand then. I changed the url's in the launch.json. Is there another config location?

9876 is the port number for ng test. I copied and pasted it from vscode's angular configuration on github.

**Comment by Godrules500** [comment] 2019-07-03 12:28
Is there another way to determine and close other chrome instances? I restarted and killed all node and chrome instances from task manager.

Also, my machine has been off for 16 hours, opened chrome to respond to this, ran my vscode config, and I still get the issue this morning.

**Comment by roblourens** [comment] 2019-07-03 18:52
You can set an attribute named "port" in your launch config, that is what I'm talking about.

**Comment by Godrules500** [comment] 2019-07-03 20:13
Still nothing. If I take out the pre launch task it'll load localhost (without the 4200). If I add the preLaunchTask it get's me the same error.

I don't have chrome opened at all. every instance of chrome is closed, ie, edge, firefox are closed via the task manager.  Unless there is another way for a chrome tab to be open, then there is no instance of localhost:9876 running.


    {
      "name": "Open Please",
      "type": "chrome",
      "request": "launch",
      "preLaunchTask": "npm: start", //this runs ng serve
      "port": 4200,
      "url": "http://localhost",
      "webRoot": "${workspaceFolder}",
      "trace": true
    },

**Comment by roblourens** [comment] 2019-07-04 03:56
"port" is the debug port not your server port. I'm just suggesting that you could set it to some other number to make sure there is no conflict with something using that port. If you set it to 4200 it will definitely not work.

**Comment by yaminger** [comment] 2019-07-04 07:23
![18](https://user-images.githubusercontent.com/38683976/60646671-7d763200-9e6e-11e9-97b7-aff245e71f65.png)

版本: 1.36.0 (user setup)
提交: 0f3794b38477eea13fb47fbe15a42798e6129338
日期: 2019-07-03T13:25:46.372Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

我和你遇到了同样的问题，代码没有做任何修改，但无法通过vscode启动chrome调试。你可暂时使用下面方法：项目编译成功后，直接在chrome里输入127.0.0.1:4445，不启动vscode调试。

google translate：
I encountered the same problem with you, the code did not make any changes, but I could not start chrome debugging via vscode. You can temporarily use the following method: After the project is successfully compiled, enter 127.0.0.1:4445 directly in chrome, do not start vscode debugging.

**Comment by yaminger** [comment] 2019-07-06 02:25
我刚刚使用下面的方法解决了这个问题。问题可能是RXJS导致的，如果你也安装了RXJS，可以试一下。
使用下面的命令检查你的npm是否全局安装过RXJS插件：
`npm list -g --dept 0`
如果列表中有RXJS，卸载该模块，重启电脑。
编译项目，调试就可使用了。

google translate:
I just solved this problem using the following method. The problem may be caused by RXJS. If you have also installed RXJS, you can try it.
Use the following command to check if your npm has installed the RXJS plugin globally:
`npm list -g --dept 0`
If there is RXJS in the list, uninstall the module and restart the computer.
Compile the project and debug it.

**Comment by Godrules500** [comment] 2019-07-08 12:38
Nah, I do not have RXJS installed so this doesn't fix it for me. The only thing that seems to fix it is if I close all of the node servers that are running when I boot the machine.

**Comment by Godrules500** [comment] 2019-07-08 12:42
Correction, apparently that is not what fixed it. Just closed all node services and I'm still receiving the same error. Any other ideas I can try?

**Comment by roblourens** [comment] 2019-07-10 18:45
That error would sound like there is another server listening on the default chrome debug port, you can try setting the `port` variable in your launch config to choose another one.

**Comment by Godrules500** [comment] 2019-07-16 11:54
I've tried that, and it still is not resolving the issue sadly.  I'm having to use edge for debugger and it is so much slower. 

Is no one else having the same issue?

**Comment by roblourens** [comment] 2019-07-19 01:35
If it helps to debug at all, you can just open `http://localhost:<port>/json` in a web browser, after Chrome opens, and check the result. That is what the extension does to begin establishing a connection. If you get a response when chrome is not open, then there is definitely something else on that port.

**Comment by Godrules500** [comment] 2019-07-23 13:50
I will say that if I put the port to 4100 it works.  I still don't know why it won't work if I put port 4200. Could it be a globally installed node module?

    {
      "name": "ng serve",
      "type": "chrome",
      "request": "launch",
      "preLaunchTask": "npm: start",
      "port": 4100,
      "url": "http://localhost:4200/#",
      "webRoot": "${workspaceFolder}"
    },

**Comment by roblourens** [comment] 2019-07-23 17:53
Judging from your url it looks like your server is running on 4200. Chrome and your server need to be using different ports.

**Closed by roblourens** 2019-07-23 17:53 UTC
Labels: needs more info
