### ISSUE TITLE
nwjs support

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode-chrome-debug#153] opened 2016-04-21 05:48 UTC
I'm not being able to remote debug chrome, this is my launch.json:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "webRoot": "${workspaceRoot}/public/js",
            "request": "attach",
            "diagnosticLogging": true,
            "port": 9222,
            "sourceMaps": true
        }
    ]
}
```

the console displays:

```
 ›OS: win32 ia32
  ›Node version: v5.10.0
  ›Adapter version: 0.2.5
  ›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›attach({"name":"Attach with sourcemaps","type":"chrome","webRoot":"g:\\www\\neuro/public/js","request":"attach","diagnosticLogging":true,"port":9222,"sourceMaps":true,"noDebug":false})
  ›Attempting to attach on port 9222
  ›Error: Got response from target app, but no valid target pages found
    at Object.errP (F:\Users\Paulo\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-0.2.5\out\webkit\utilities.js:341:13)
    at F:\Users\Paulo\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-0.2.5\out\webkit\webKitConnection.js:162:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"[debugger-for-chrome] Got response from target app, but no valid target pages found"}
  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

to make sure that `remote-debugger-port` in chrome is working, when I close it, it displays:

```
  ›OS: win32 ia32
  ›Node version: v5.10.0
  ›Adapter version: 0.2.5
  ›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
  ›attach({"name":"Attach with sourcemaps","type":"chrome","webRoot":"g:\\www\\neuro/public/js","request":"attach","diagnosticLogging":true,"port":9222,"sourceMaps":true,"noDebug":false})
  ›Attempting to attach on port 9222
  ›Error: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222
    at Object.errP (F:\Users\Paulo\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-0.2.5\out\webkit\utilities.js:341:13)
    at F:\Users\Paulo\.vscode-insiders\extensions\msjsdiag.debugger-for-chrome-0.2.5\out\webkit\webKitConnection.js:164:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"[debugger-for-chrome] Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:9222"}
  ›From client: disconnect({"restart":false})
  ›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

using windows 10 x64, chrome 50.0.2661.75, vscode 1.0.1-insider

**Comment by roblourens** [comment] 2016-04-22 23:13
Your config looks right. Can you go to "localhost:9222" when Chrome is open, and see if any pages show up? If so, can you give me the output of "localhost:9222/json"?

And maybe try checking for any remaining background processes of Chrome after you close it, although this isn't the problem that's usually caused by that.

**Comment by pocesar** [comment] 2016-04-23 20:01
Here's the output:

``´json
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/19F7304F-54C7-49CA-A825-2D36F2A83D0E",
   "id": "19F7304F-54C7-49CA-A825-2D36F2A83D0E",
   "title": "Inspectable pages",
   "type": "page",
   "url": "http://localhost:9222/json",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/19F7304F-54C7-49CA-A825-2D36F2A83D0E"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/CF7860F0-88D2-4128-B204-AD5E29214FAC",
   "id": "CF7860F0-88D2-4128-B204-AD5E29214FAC",
   "title": "Developer Tools - http://altaenergia.local-academialowcost.com.br/",
   "type": "other",
   "url": "chrome-devtools://devtools/bundled/inspector.html?&remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@ffad3c52452e415ab24c9cad1bae22eeb7428092/&can_dock=true&dockSide=undocked",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/CF7860F0-88D2-4128-B204-AD5E29214FAC"
}, {
   "description": "",
   "id": "2C34DF55-A355-467E-B71A-997074AE54F9",
   "thumbnailUrl": "/thumb/2C34DF55-A355-467E-B71A-997074AE54F9",
   "title": "Academias Alta Energia",
   "type": "page",
   "url": "http://altaenergia.local-academialowcost.com.br/#!/"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/4153A529-872A-40A4-B86C-114BE85D7EA5",
   "faviconUrl": "chrome://extension-icon/ighdmehidhipcmcojjgiloacoafjmpfk/24/1",
   "id": "4153A529-872A-40A4-B86C-114BE85D7EA5",
   "title": "AngularJS Batarang",
   "type": "background_page",
   "url": "chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/4153A529-872A-40A4-B86C-114BE85D7EA5"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/ACE0E2C7-C0D4-4D94-92DF-5924D2443D9B",
   "id": "ACE0E2C7-C0D4-4D94-92DF-5924D2443D9B",
   "title": "Worker pid:15708",
   "type": "service_worker",
   "url": "https://www.google.com.br/_/chrome/newtab-serviceworker.js",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/ACE0E2C7-C0D4-4D94-92DF-5924D2443D9B"
} ]
```

**Comment by pocesar** [comment] 2016-04-23 20:05
maybe the "url" parameter in the launch.json should accept wildcards? like setting `"url":"*academialowcost*"` should find the suitable tab

**Comment by roblourens** [comment] 2016-04-25 15:56
Hm, that looks right. The error implies that it didn't get that response, or that it's invalid JSON for some reason. Or that Chrome isn't starting up within the ~6s timeout. I should add more logging around that.

It actually doesn't pull from `localhost:9222`, but from `127.0.0.1:9222`. Is there any reason that wouldn't resolve to localhost on your machine?

**Comment by pocesar** [comment] 2016-04-25 16:26
```
g:\www\marcos>ping localhost

Pinging Paulo-PC [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

Ping statistics for ::1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

maybe it doesn't like ipv6?

**Comment by roblourens** [comment] 2016-04-25 16:46
Hm, I see the same. I just noticed that yours uses Node 5.1 where mine is using Node 4.1.1. I thought that Code used a fixed version of Node per Code version. Is this a newer version of Code than 1.0? Otherwise, that definitely may be relevant and I need to investigate.

**Comment by pocesar** [comment] 2016-04-25 18:20
I'm currently using 1.0.1-insiders, but the debugger chrome plugin version is 0.2.5, and node 5.11.0 x64

**Comment by roblourens** [comment] 2016-04-26 01:47
I see, I haven't tested it with Node 5 or any recent insider's build, so that could be the culprit. I don't see offhand how that could cause this problem but it definitely stands out as a difference. I'll investigate.

**Comment by galvesribeiro** [comment] 2016-05-31 04:05
Guys any solution for that problem? I'm with exactly same problem... I'm just using latest Chrome (51.0.2704.63 m), VSCode latest stable (1.1.1) and Debugger for Chrome extensions 0.3.1.

This is the error:
```
›OS: win32 ia32
›Node version: v5.10.0
›Adapter version: 0.0.5
›initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true})
›attach({"name":"Attach with sourcemaps","type":"chrome","request":"attach","port":9222,"sourceMaps":true,"webRoot":"c:\\Dev\\Samples\\dietsample\\data","diagnosticLogging":true,"noDebug":false})
›Attempting to attach on port 9222
›Error: Got response from target app, but no valid target pages found
at Object.errP (C:\Users\gutem\.vscode\extensions\msjsdiag.debugger-for-chrome-0.3.1\node_modules\vscode-chrome-debug-core\out\src\utils.js:209:13)
at C:\Users\gutem\.vscode\extensions\msjsdiag.debugger-for-chrome-0.3.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:178:26
at process._tickCallback (internal/process/next_tick.js:103:7)
›To client: {"seq":0,"type":"response","request_seq":2,"command":"attach","success":false,"message":"[debugger-for-chrome] Got response from target app, but no valid target pages found"}
›From client: disconnect({"restart":false})
›To client: {"seq":0,"type":"response","request_seq":3,"command":"disconnect","success":true}
```

And this is the json response for http://localhost:9222/json 

```
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/FFE11F8E-2423-44FC-9A06-D3002DCC85BA",
   "faviconUrl": "chrome://extension-icon/nochadnphaoigfjnaclpecjelllocobm/24/1",
   "id": "FFE11F8E-2423-44FC-9A06-D3002DCC85BA",
   "title": "angular2-quickstart",
   "type": "app",
   "url": "chrome-extension://nochadnphaoigfjnaclpecjelllocobm/dashboard",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/FFE11F8E-2423-44FC-9A06-D3002DCC85BA"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/26D97B89-60F5-4F43-AEF7-7945C10D8ED3",
   "faviconUrl": "chrome://extension-icon/nochadnphaoigfjnaclpecjelllocobm/24/1",
   "id": "26D97B89-60F5-4F43-AEF7-7945C10D8ED3",
   "title": "angular2-quickstart",
   "type": "background_page",
   "url": "chrome-extension://nochadnphaoigfjnaclpecjelllocobm/_generated_background_page.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/26D97B89-60F5-4F43-AEF7-7945C10D8ED3"
} ]
```

Really appreciate any workaround for that...

**Comment by auchenberg** [comment] 2016-05-31 10:39
@galvesribeiro Looking at the respons you get from `http://localhost:9222/json` Chrome doesn't have any tabs open. Is this correct? 

In your case you either need to change your `launch.json` to use `"request": "launch"` instead of `attach` to make VSCode open a new tab in Chrome OR make sure you have your a tab open in Chrome that matches your `url` property in your `launch.json` file.

It's a bit cumbersome, but Chrome and VSCode needs to match before it can connect to the right tab.

**Comment by galvesribeiro** [comment] 2016-05-31 14:13
@auchenberg its not Chrome itself, it is a hosted chromium (http://nwjs.io) which has the debugging/dev tools enabled... I launch it with `--remote-debugging-port=9222` and if I open http://localhost:9222 it opens the debug list, I select one of them and dev tools is opened on chrome itself just fine. So, I would assume that attach should do the same...

For the url, if you see on the list, the url is chrome-extension://nochadnphaoigfjnaclpecjelllocobm/dashboard for instance... We just don't get it connected :(

**Comment by auchenberg** [comment] 2016-05-31 19:43
Ahh @galvesribeiro, it makes sense then. For now the debugger only supports Chrome "pages" and not other Chrome-like instances like nwjs or electron.

We filter out debug targets where the `type !== 'app'`, which is the reason why the target is getting rejected. See https://github.com/Microsoft/vscode-chrome-debug-core/blob/df72f63c8f650296714fb8e489c081eb2d7ace88/src/chrome/chromeConnection.ts#L158

I'll reference your issue on the [Add support for NW.JS feature request](https://github.com/Microsoft/vscode-chrome-debug-core/issues/18)

**Comment by galvesribeiro** [comment] 2016-05-31 20:00
Ok so if I hack the js file from the extension I would get it to work?

**Comment by galvesribeiro** [comment] 2016-05-31 20:17
Ok... looks like the hack somehow worked...

```
var pages = responseArray;//.filter(function (target) { return target && (!target.type || target.type === 'page'); });
```
That and this config: 

```
{
            "name": "NW.js",
            "type": "chrome",
            "request": "launch",
            "runtimeExecutable": "nw",            
            "webRoot": "${workspaceRoot}",
            "runtimeArgs": [
                "${workspaceRoot}",
                "--mixed-context",
                "--remote-debugging-port=9222"
            ],
            "sourceMaps": true,
            "diagnosticLogging": true,
            "port": 9222
        }
```

It launch nw (NW dir is on my PATH), open the app just fine however, no breakpoint is ever hit and I see lots of messages like:

```
›From target: {"id":2,"result":{}}
›To client: {"seq":0,"type":"event","event":"initialized"}
›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
›From client: setBreakpoints({"source":{"path":"c:\\Dev\\Samples\\dietsample\\data\\app\\dashboard.component.js"},"lines":[26],"breakpoints":[{"line":26}]})
›From client: setBreakpoints({"source":{"path":"c:\\Dev\\Samples\\dietsample\\data\\app\\dashboard.component.ts"},"lines":[28],"breakpoints":[{"line":28}]})
›SourceMaps.setBP: c:\Dev\Samples\dietsample\data\app\dashboard.component.js can't be resolved to a loaded script.
›SourceMaps.setBP: c:\Dev\Samples\dietsample\data\app\dashboard.component.ts can't be resolved to a loaded script.
```
No breakpoint is loaded and stay gray without ever hit... Any clues @auchenberg ?

**Comment by auchenberg** [comment] 2016-05-31 21:08
@galvesribeiro Looks like a source mapping issue. You might need to tweak the `"webRoot": "${workspaceRoot}",` to match your output folder from the logs. Look further in the logs ;)

Please contribute to the above issue if you figure out a way to get NWJS working. It would be great, as it's unsupported for now.

**Comment by galvesribeiro** [comment] 2016-05-31 22:21
Sure, as getting that to work here and I'll push a PR on this debugger and on docs :) 

Tried to change the "webRoot" but there is not any feasible options on this project as you can see on that structure:


And this is the tsconfig.json:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}
```
It debug perfectly if we run in a browser but even with the hack on the debug extensions got no lucky on nwjs :(

**Comment by galvesribeiro** [comment] 2016-06-02 16:15
@auchenberg finally got that thing to work with help of some nw.js folks. In fact, it works for any kind of chromium-based project as long as they support the Chrome debug protocol. 

I see no point on have those filters [here](https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeConnection.ts#L158) and [here](https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L617). I'm removing it and making a PR linking your issue if no one else has any objections.

Thanks for the support!

**Comment by auchenberg** [comment] 2016-06-02 20:24
That's cool to hear! We'll review the PR and move the discussion to here then. Thanks a bunch 😸

**Comment by pietgk** [comment] 2016-06-23 09:49
i have a similar issue:
launch.json is:
{
	"version": "0.2.0",
	"configurations": [
	    {
                "name": "Debug",
                "type": "chrome",
                "request": "launch",
                "diagnosticLogging": true,
                "webRoot": "${workspaceRoot}",
                "url": "http://localhost:3000/index.html", 
                "userDataDir": "${workspaceRoot}/.vscode/chrome",
                "sourceMaps": true,
                "preLaunchTask": "development"
            }
	]
}

logging is:

  ›OS: darwin x64
  ›Node: v5.10.0
  ›vscode-chrome-debug-core: 0.1.6
  ›debugger-for-chrome: 0.4.4
  ›spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--user-data-dir=/Users/grop/dev/carservice/develop/carservice_app/apps/ownerApp/.vscode/chrome","http://localhost:3000/index.html"])
  ›Attempting to attach on port 9222
  ›Warning: Can't find a target that matches: http://localhost:3000/index.html. Available pages: []

**http://127.0.0.1/json** (as used in the code referenced by  https://github.com/Microsoft/vscode-chrome-debug-core/blob/df72f63c8f650296714fb8e489c081eb2d7ace88/src/chrome/chromeConnection.ts#L158) returns:
[  ]

http://localhost:9222/json returns
[ {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/B6F27284-C200-43AB-883C-86ED1595335C",
   "id": "B6F27284-C200-43AB-883C-86ED1595335C",
   "title": "localhost:9222/json",
   "type": "page",
   "url": "http://localhost:9222/json",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/B6F27284-C200-43AB-883C-86ED1595335C"
}, {
   "description": "",
   "devtoolsFrontendUrl": "/devtools/inspector.html?ws=localhost:9222/devtools/page/F9E9EC49-531D-4D25-91BA-A07D22FFCB28",
   "id": "F9E9EC49-531D-4D25-91BA-A07D22FFCB28",
   "title": "React Hot Boilerplate",
   "type": "page",
   "url": "http://localhost:3000/index.html",
   "webSocketDebuggerUrl": "ws://localhost:9222/devtools/page/F9E9EC49-531D-4D25-91BA-A07D22FFCB28"
} ]

any tips would be appreciated.

thx in advance

**Comment by auchenberg** [comment] 2016-09-26 23:29
Closing this, as this feature is out of scope for this project. A new debugger should be build for NW.js/Electron.

**Closed by auchenberg** 2016-09-26 23:29 UTC
Labels: enhancement
