### ISSUE TITLE
Problem with set breakpoints with latest VS Code version 0.10.10

### ISSUE THREAD

**Issue by saskomateski** [Microsoft/vscode-chrome-debug#115] opened 2016-03-08 08:47 UTC
After installing latest VS Code version 0.10.10 we are having problems when setting breakpoints - the debugger is not stopping on breakpoints.

**Comment by 4zriel** [comment] 2016-03-08 09:18
Same story...yesterday everything on same launch.json settings worked fine but today after update to 0.10.10 debugger is usless :(

**Comment by marko-baric-travcorp** [comment] 2016-03-08 11:13
Same problem here. Looks like there is a problem related to setting "webRoot" value which might be related to this. There is a separate issue for this.

**Comment by saskomateski** [comment] 2016-03-08 12:59
Workaround for the problem ca be found in Issue #117

**Comment by andersrydman** [comment] 2016-03-08 14:17
We're experiencing the same thing as well.

**Comment by auchenberg** [comment] 2016-03-08 17:27
Thanks for reporting this! Stay tuned.

**Comment by auchenberg** [comment] 2016-03-08 17:37
Duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/117

README has been updated with new defaults for `webRoot`

**Closed by auchenberg** 2016-03-08 17:37 UTC
Labels: duplicate
