### ISSUE TITLE
Cant always set breakpoints where you want them

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#161] opened 2016-05-23 21:06 UTC
![image](https://cloud.githubusercontent.com/assets/1707226/15484406/fadf375c-218d-11e6-8a2e-e7e9f74c7059.png)
if i try to set a breakpoint on the yellow highlighted line it tries to set it 3 lines below.
However if i add the ```debugger;``` statement in the same place it works fine.

**Comment by auchenberg** [comment] 2016-05-24 09:48
Hi @justin-romano 

Are you using any form of sourcemaps? Can you share your setup and configs?

**Comment by roblourens** [comment] 2016-06-07 05:08
Probably a dupe of #162

**Closed by roblourens** 2016-06-07 05:08 UTC
Labels: bug
