### ISSUE TITLE
Dynamic edit and continue by real time saving editor changes to the DOM

### ISSUE THREAD

**Issue by justin-romano** [Microsoft/vscode-chrome-debug#67] opened 2015-12-11 02:33 UTC
I have seen this done with other editor chrome plugins so i figured this must be possible. Would make this even awesomer. (Feature request)

**Comment by roblourens** [comment] 2015-12-11 02:49
I think the Chrome API allows it, that would be cool

**Comment by justin-romano** [comment] 2016-02-03 04:25
Well Devtools can do it if you have it set up right so i would concur

**Comment by auchenberg** [comment] 2016-02-12 22:16
If we can detect file changes from VS Code, we can push the changes over via the `setScriptSource` API.

Inspiration can be [amokjs.com](http://amokjs.com/) that's using a file watcher with `setScriptSource` to make this happen.

**Comment by justin-romano** [comment] 2016-02-13 02:53
Would be really cool. Is setting the current position posible also. I have
not seen the in anything other than vs.

**Comment by matthias-lubbers** [comment] 2016-02-29 09:32
Brackets (front end editor, also nodejs based) allows for realtime editing of css and html as well. Would be nice to have this in Code.

**Comment by auchenberg** [comment] 2016-02-29 17:43
@justin-romano I'm a bit unsure what you mean by `setting the current position`. Can you clarify?

**Comment by justin-romano** [comment] 2016-02-29 23:01
In visual studio you have always been able to place the running code
position at any point in the same functional scope. You can also do this in
Javascript and all languages are supported. in machine code its equivalent
to setting the instruction pointer (IP) register.
We use to do this in the old debuggers. Works a treat.

On Tue, Mar 1, 2016 at 6:43 AM, Kenneth Auchenberg <notifications@github.com
> wrote:

> @justin-romano <https://github.com/justin-romano> I'm a bit unsure what
> you mean by setting the current position. Can you clarify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode-chrome-debug/issues/67#issuecomment-190305907>
> .
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by roblourens** [comment] 2016-03-01 00:22
Ah, "Set next statement", F12 supports this too. Not sure whether the Chrome debug protocol has this support though.

**Comment by justin-romano** [comment] 2016-03-01 04:59
no i would not have thought so. It sort of does with edit-and-continue i
have seen the cursor jump context to just prior to the line you are editing.

On Tue, Mar 1, 2016 at 1:22 PM, Rob Lourens <notifications@github.com>
wrote:

> Ah, "Set next statement", F12 supports this too. Not sure whether the
> Chrome debug protocol has this support though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Microsoft/vscode-chrome-debug/issues/67#issuecomment-190465613>
> .
>



-- 
Justin Romaine
Senior Systems Architect
Spark Dental Technology
justin.romaine@gmail.com
ph 021 764 506
hm 09 445 9166

**Comment by felixfbecker** [comment] 2016-03-15 11:07
This should only require a watch on the `webRoot`

**Comment by auchenberg** [comment] 2016-09-26 23:28
Duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/216

**Closed by auchenberg** 2016-09-26 23:28 UTC
Labels: enhancement
