### ISSUE TITLE
Budo (+Browserify): Breakpoint ignored because generated code not found(source map problem?)

### ISSUE THREAD

**Issue by sladiri** [Microsoft/vscode-chrome-debug#480] opened 2017-08-23 14:19 UTC
Since your Readme states that inlined sourcemaps are ignored, I tried _mapstraction_ to extract the maps to a file. The bundle.js itself is served from memory by the _Budo_ web-server.

- VS Code Version:
1.15.1

Steps to reproduce:

1. start Budo development server which uses Browserify to transpile with Babel
`budo src/browserEntryPoint/boundary.js:static/dist/bundle.js --host localhost --pushstate --live -- -t babelify -p [ mapstraction "static/dist/bundle.js.map" ]`.
2. Launch Chrome task for this extension. The budo server log, after I load the page in Chrome:
```
[0002] info  Server running at http://localhost:9966/ (connect)
[0002] info  LiveReload running
[0010] 8458ms     2.3MB (browserify)
[0024] 2ms           0B GET    200 /static/dist/bundle.js
[0024] 68ms          0B GET    200 /budo/livereload.js
[0024] 15ms       2.7MB GET    200 /static/dist/bundle.js.map
```
3. Breakpoints in VSCode do not work. (If I open developer tools in Chrome, the external maps are used correctly.)

my launch config:
```
{
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:9966",
      "webRoot": "${workspaceRoot}",
      "trace": "verbose"
    }
```

the trace log:
```
Verbose logs are written to:
C:\Users\sladj\AppData\Local\Temp\vscode-chrome-debug.txt
OS: win32 x64
Adapter node: v7.4.0 x64
vscode-chrome-debug-core: 3.16.5
4:25:37 PM, 8/23/2017
debugger-for-chrome: 3.1.8
From client: initialize({"clientID":"vscode","adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsRestartFrame":true,"supportsExceptionInfoRequest":true,"supportsDelayedStackTraceLoading":true,"supportsValueFormattingOptions":true,"supportsRestartRequest":true}}
From client: launch({"type":"chrome","request":"launch","name":"Launch Chrome against localhost","url":"http://localhost:9966","webRoot":"c:\\Users\\sladj\\repos\\sam-cerebral","trace":"verbose","__sessionId":"7ae1834f-8693-4e4a-99a4-58528b6a6669"})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStarted","data":{"request":"launch","args":["type","request","name","url","webRoot","trace","__sessionId","sourceMaps","sourceMapPathOverrides","skipFileRegExps"]}}}
Discovering targets via http://127.0.0.1:9222/json
[chromeSpawnHelper] spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--user-data-dir=C:\\Users\\sladj\\AppData\\Local\\Temp\\vscode-chrome-debug-userdatadir_9222","http://localhost:9966"])

got chrome PID: 18712
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"targetCount","data":{"numTargets":2}}}
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/57949b4c-2bd4-4c36-9c6f-667d09cecf5b","id":"57949b4c-2bd4-4c36-9c6f-667d09cecf5b","title":"SAM - Cerebral","type":"page","url":"http://localhost:9966/","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/57949b4c-2bd4-4c36-9c6f-667d09cecf5b"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/57949b4c-2bd4-4c36-9c6f-667d09cecf5b
→ To target: "{\"id\":1,\"method\":\"Debugger.setBlackboxPatterns\",\"params\":{\"patterns\":[\"^chrome-extension:.*\"]}}"
→ To target: "{\"id\":2,\"method\":\"Console.enable\"}"
→ To target: "{\"id\":3,\"method\":\"Debugger.enable\"}"
→ To target: "{\"id\":4,\"method\":\"Runtime.enable\"}"
→ To target: "{\"id\":5,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
→ To target: "{\"id\":6,\"method\":\"Runtime.run\"}"
→ To target: "{\"id\":7,\"method\":\"Page.enable\"}"
→ To target: "{\"id\":8,\"method\":\"Network.enable\",\"params\":{}}"
← From target: {"id":1,"result":{}}
← From target: {"id":2,"result":{}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"26","url":"http://localhost:9966/static/vendor/babel-helpers.js","startLine":0,"startColumn":0,"endLine":558,"endColumn":0,"executionContextId":1,"hash":"58992260D305BC262EA6FC348B4DE5F8349C9CD4","executionContextAuxData":{"isDefault":true,"frameId":"2416.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":14184}}
→ To target: "{\"id\":9,\"method\":\"Debugger.getPossibleBreakpoints\",\"params\":{\"start\":{\"scriptId\":\"26\",\"lineNumber\":0,\"columnNumber\":0},\"end\":{\"scriptId\":\"26\",\"lineNumber\":1,\"columnNumber\":0},\"restrictToFunction\":false}}"
Paths.scriptParsed: resolved http://localhost:9966/static/vendor/babel-helpers.js to c:\Users\sladj\repos\sam-cerebral\static\vendor\babel-helpers.js. webRoot: c:\Users\sladj\repos\sam-cerebral
← From target: {"id":3,"result":{}}
← From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"http://localhost:9966","name":"","auxData":{"isDefault":true,"frameId":"2416.1"}}}}
← From target: {"id":4,"result":{}}
← From target: {"id":5,"result":{}}
← From target: {"error":{"code":-32601,"message":"'Runtime.run' wasn't found"},"id":6}
← From target: {"id":7,"result":{}}
← From target: {"id":8,"result":{}}
→ To target: "{\"id\":10,\"method\":\"Debugger.setAsyncCallStackDepth\",\"params\":{\"maxDepth\":0}}"
← From target: {"id":9,"result":{"locations":[]}}
To client: {"seq":0,"type":"event","event":"initialized"}
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":0,"source":{"name":"babel-helpers.js","path":"http://localhost:9966/static/vendor/babel-helpers.js","sourceReference":1000}}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"http://localhost:9966/static/vendor/babel-helpers.js"}}
← From target: {"id":10,"result":{}}
→ To target: "{\"id\":11,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"navigator.userAgent\",\"silent\":true}}"
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"32","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":19,"executionContextId":1,"hash":"261450710E53FAF08507A2B5A8FCEC05872EBA18","executionContextAuxData":{"isDefault":true,"frameId":"2416.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":19}}
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":1,"source":{"name":"VM32","path":"VM32","sourceReference":1001}}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"<eval>/VM32"}}
← From target: {"id":11,"result":{"result":{"type":"string","value":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"}}}
Target userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36
→ To target: "{\"id\":12,\"method\":\"Network.setCacheDisabled\",\"params\":{\"cacheDisabled\":false}}"
← From target: {"id":12,"result":{}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
→ To target: "{\"id\":13,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"uncaught\"}}"
← From target: {"id":13,"result":{}}
To client: {"seq":0,"type":"response","request_seq":3,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":4,"command":"configurationDone","success":true}
From client: threads(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"threads","success":true,"body":{"threads":[{"id":1,"name":"Chrome"}]}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"33","url":"http://localhost:9966/budo/livereload.js","startLine":0,"startColumn":0,"endLine":0,"endColumn":20716,"executionContextId":1,"hash":"75E312D242A1B862AA816812A32CB47C9468F026","executionContextAuxData":{"isDefault":true,"frameId":"2416.1"},"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":20716}}
Paths.scriptParsed: could not resolve http://localhost:9966/budo/livereload.js to a file under webRoot: c:\Users\sladj\repos\sam-cerebral. It may be external or served directly from the server's memory (and that's OK).
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":2,"source":{"name":"livereload.js","path":"http://localhost:9966/budo/livereload.js","sourceReference":1002}}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"http://localhost:9966/budo/livereload.js"}}
← From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","startLine":0,"startColumn":0,"endLine":74610,"endColumn":34,"executionContextId":1,"hash":"7B559010E351FD47C6C95A50D90EAF7026416D34","executionContextAuxData":{"isDefault":true,"frameId":"2416.1"},"isLiveEdit":false,"sourceMapURL":"bundle.js.map","hasSourceURL":false,"isModule":false,"length":2316161}}
Paths.scriptParsed: could not resolve http://localhost:9966/static/dist/bundle.js to a file under webRoot: c:\Users\sladj\repos\sam-cerebral. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:9966/static/dist/bundle.js by URI: bundle.js.map and webRoot: c:\Users\sladj\repos\sam-cerebral
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:9966/static/dist/bundle.js.map
To client: {"seq":0,"type":"event","event":"script","body":{"reason":"new","script":{"id":3,"source":{"name":"bundle.js","path":"http://localhost:9966/static/dist/bundle.js","sourceReference":1003}}}}
To client: {"seq":0,"type":"event","event":"scriptLoaded","body":{"path":"http://localhost:9966/static/dist/bundle.js"}}
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"debug","text":"Download the React DevTools for a better development experience: https://fb.me/react-devtools","url":"http://localhost:9966/static/dist/bundle.js","line":49910,"column":17}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"debug","args":[{"type":"string","value":"Download the React DevTools for a better development experience: https://fb.me/react-devtools"}],"executionContextId":1,"timestamp":1503498339133.132,"stackTrace":{"callFrames":[{"functionName":"","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":49909,"columnNumber":16},{"functionName":"526../ReactDOMComponentTree","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":49947,"columnNumber":3},{"functionName":"s","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":0,"columnNumber":253},{"functionName":"","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":0,"columnNumber":304},{"functionName":"496../lib/ReactDOM","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":44552,"columnNumber":17},{"functionName":"s","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":0,"columnNumber":253},{"functionName":"","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":0,"columnNumber":304},{"functionName":"731.../appShell/boundary","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":73675,"columnNumber":16},{"functionName":"s","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":0,"columnNumber":253},{"functionName":"e","scriptId"[...]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"Download the React DevTools for a better development experience: https://fb.me/react-devtools\n"}}
Download the React DevTools for a better development experience: https://fb.me/react-devtools
SourceMap: creating for http://localhost:9966/static/dist/bundle.js
SourceMap: sourceRoot: 
SourceMap: sources: ["node_modules/browser-pack/_prelude.js","node_modules/@cerebral/router/lib/base.js","node_modules/@cerebral/router/lib/index.js","node_modules/@cerebral/router/lib/router.js","node_modules/@cerebral/router/lib/utils.js","node_modules/addressbar/index.js","node_modules/argsarray/index.js","node_modules/base64-js/index.js","node_modules/browser-resolve/empty.js","node_modules/buffer-from/index.js","node_modules/buffer/index.js","node_modules/cerebral/devtools.js","node_modules/cerebral/index.js","node_modules/cerebral/lib/Compute.js","node_modules/cerebral/lib/Controller.js","node_modules/cerebral/lib/DependencyStore.js","node_modules/cerebral/lib/DependencyTracker.js","node_modules/cerebral/lib/Model.js","node_modules/cerebral/lib/Module.js","node_modules/cerebral/lib/Provide.js","node_modules/cerebral/lib/UniversalController.js","node_modules/cerebral/lib/devtools/index.js","node_modules/cerebral/lib/index.js","node_modules/cerebral/lib/operators/concat.js","node_modules/cerebral/lib/operators/debounce.js","node_modules/cerebral/lib/operators/equals.js","node_modules/cerebral/lib/operators/increment.js","node_modules/cerebral/lib/operators/index.js","node_modules/cerebral/lib/operators/input.js","node_modules/cerebral/lib/operators/merge.js","node_modules/cerebral/lib/operators/pop.js","node_modules/cerebral/lib/operators/push.js","node_modules/cerebral/lib/operators/set.js","node_modules/cerebral/lib/operators/shift.js","node_modules/cerebral/lib/operato[...]
SourceMap: webRoot: c:\Users\sladj\repos\sam-cerebral
SourceMap: no sourceRoot specified, using webRoot + script path dirname: c:\Users\sladj\repos\sam-cerebral\static\dist
SourceMaps.scriptParsed: http://localhost:9966/static/dist/bundle.js was just loaded and has mapped sources: ["c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\browser-pack\\_prelude.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\@cerebral\\router\\lib\\base.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\@cerebral\\router\\lib\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\@cerebral\\router\\lib\\router.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\@cerebral\\router\\lib\\utils.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\addressbar\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\argsarray\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\base64-js\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\browser-resolve\\empty.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\buffer-from\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\buffer\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\cerebral\\devtools.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\cerebral\\index.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\cerebral\\lib\\Compute.js","c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\cereb[...]
← From target: {"method":"Page.loadEventFired","params":{"timestamp":710706.360825}}
← From target: {"method":"Page.frameStoppedLoading","params":{"frameId":"2416.1"}}
← From target: {"method":"Page.domContentEventFired","params":{"timestamp":710706.364311}}
← From target: {"method":"Debugger.scriptFailedToParse","params":{"scriptId":"35","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":0,"executionContextId":1,"hash":"06157BF3E4E4F1BA4CB5762843D429DC872EBA18","executionContextAuxData":{"isDefault":true,"frameId":"2416.1"},"sourceMapURL":"","hasSourceURL":false,"isModule":false,"length":0,"stackTrace":{"callFrames":[{"functionName":"xhr.onreadystatechange","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":28433,"columnNumber":21}]}}}
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"Could not connect to remote DB.","url":"http://localhost:9966/static/dist/bundle.js","line":73735,"column":13}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"Could not connect to remote DB."}],"executionContextId":1,"timestamp":1503498340599.132,"stackTrace":{"callFrames":[{"functionName":"getRemote","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":73734,"columnNumber":12}]}}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"Could not connect to remote DB.\n"}}
Could not connect to remote DB.
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"[cached_blog] connected","url":"http://localhost:9966/static/dist/bundle.js","line":73720,"column":11}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"[cached_blog] connected"},{"type":"string","value":"\n"},{"type":"object","subtype":"array","className":"Array","description":"Array(2)","objectId":"{\"injectedScriptId\":1,\"id\":1}","preview":{"type":"object","subtype":"array","description":"Array(2)","overflow":false,"properties":[{"name":"0","type":"string","value":"id=[15034...];rev=[1-79c4b...]"},{"name":"1","type":"string","value":"id=[15034...];rev=[1-e9db6...]"}]}}],"executionContextId":1,"timestamp":1503498340678.3691,"stackTrace":{"callFrames":[{"functionName":"logDbReady","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":73719,"columnNumber":10}]}}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"output","variablesReference":100000}}
From client: variables({"variablesReference":100000})
To client: {"seq":0,"type":"response","request_seq":6,"command":"variables","success":true,"body":{"variables":[{"name":"0","value":"[cached_blog] connected \n","variablesReference":0,"evaluateName":"0"},{"name":"1","value":"Array(2) [\"id=[15034...];rev=[1-79c4b...]\", \"id=[15034...];rev=[1-e9db6...]\"]","type":"Object","variablesReference":100001,"indexedVariables":2,"namedVariables":2,"evaluateName":"1"}]}}

null: [cached_blog] connected 

null: Array(2) ["id=[15034...];rev=[1-79c4b...]", "id=[15034...];rev=[1-e9db6...]"]
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"[inMemory_blog] connected","url":"http://localhost:9966/static/dist/bundle.js","line":73720,"column":11}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"[inMemory_blog] connected"},{"type":"string","value":"\n"},{"type":"object","subtype":"array","className":"Array","description":"Array(0)","objectId":"{\"injectedScriptId\":1,\"id\":2}","preview":{"type":"object","subtype":"array","description":"Array(0)","overflow":false,"properties":[]}}],"executionContextId":1,"timestamp":1503498340711.026,"stackTrace":{"callFrames":[{"functionName":"logDbReady","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":73719,"columnNumber":10}]}}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"output","variablesReference":100002}}
From client: variables({"variablesReference":100002})
To client: {"seq":0,"type":"response","request_seq":7,"command":"variables","success":true,"body":{"variables":[{"name":"0","value":"[inMemory_blog] connected \n","variablesReference":0,"evaluateName":"0"},{"name":"1","value":"Array(0) []","type":"Object","variablesReference":100003,"indexedVariables":0,"namedVariables":2,"evaluateName":"1"}]}}

null: [inMemory_blog] connected 

null: Array(0) []
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"[cached_blog] replicated to [inMemory_blog]","url":"http://localhost:9966/static/dist/bundle.js","line":73768,"column":13}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"[cached_blog] replicated to [inMemory_blog]"},{"type":"string","value":"\n"},{"type":"string","value":"[cached_blog]: "},{"type":"object","subtype":"array","className":"Array","description":"Array(2)","objectId":"{\"injectedScriptId\":1,\"id\":3}","preview":{"type":"object","subtype":"array","description":"Array(2)","overflow":false,"properties":[{"name":"0","type":"string","value":"id=[15034...];rev=[1-79c4b...]"},{"name":"1","type":"string","value":"id=[15034...];rev=[1-e9db6...]"}]}},{"type":"string","value":"\n"},{"type":"string","value":"[inMemory_blog]: "},{"type":"object","subtype":"array","className":"Array","description":"Array(2)","objectId":"{\"injectedScriptId\":1,\"id\":4}","preview":{"type":"object","subtype":"array","description":"Array(2)","overflow":false,"properties":[{"name":"0","type":"string","value":"id=[15034...];rev=[1-79c4b...]"},{"name":"1","type":"string","value":"id=[15034...];rev=[1-e9db6...]"}]}}],"executionContextId":1,"timestamp":1503498340758.342,"stackTrace":{"callFrames":[{"functionName":"Promise.then.then","scriptId":"34","url":"http://localhost:9966/static/dist/bundle.js","lineNumber":73767,"columnNumber":12}]}}}
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"output","variablesReference":100004}}
From client: variables({"variablesReference":100004})
To client: {"seq":0,"type":"response","request_seq":8,"command":"variables","success":true,"body":{"variables":[{"name":"0","value":"[cached_blog] replicated to [inMemory_blog] \n [cached_blog]: ","variablesReference":0,"evaluateName":"0"},{"name":"1","value":"Array(2) [\"id=[15034...];rev=[1-79c4b...]\", \"id=[15034...];rev=[1-e9db6...]\"]","type":"Object","variablesReference":100005,"indexedVariables":2,"namedVariables":2,"evaluateName":"1"},{"name":"2","value":"\n","variablesReference":0,"evaluateName":"2"},{"name":"3","value":"[inMemory_blog]: ","variablesReference":0,"evaluateName":"3"},{"name":"4","value":"Array(2) [\"id=[15034...];rev=[1-79c4b...]\", \"id=[15034...];rev=[1-e9db6...]\"]","type":"Object","variablesReference":100006,"indexedVariables":2,"namedVariables":2,"evaluateName":"4"}]}}

null: [cached_blog] replicated to [inMemory_blog] 
 [cached_blog]: 
null: Array(2) ["id=[15034...];rev=[1-79c4b...]", "id=[15034...];rev=[1-e9db6...]"]
null: 

null: [inMemory_blog]: 
null: Array(2) ["id=[15034...];rev=[1-79c4b...]", "id=[15034...];rev=[1-e9db6...]"]
← From target: {"method":"Console.messageAdded","params":{"message":{"source":"console-api","level":"log","text":"Syncing [inMemory_blog] \u003C-\u003E [cached_blog]","url":"http://localhost:9966/static/dist/bundle.js","line":73795,"column":11}}}
← From target: {"method":"Runtime.consoleAPICalled","params":{"type":"log","args":[{"type":"string","value":"Syncing [inMemory_blog] \u003C-\u003E [cached_blog]"},{"type":"object","className":"Sync","description":"Sync","objectId":"{\"injectedScriptId\":1,\"id\":5}","preview":{"type":"object","description":"Sync","overflow":true,"properties":[{"name":"canceled","type":"boolean","value":"false"},{"name":"push","type":"object","value":"Replication"},{"name":"pull","type":"object","value":"Replication"},{"name":"pushPaused","type":"boolean","value":"true"},{"name":"pullPaused","type":"boolean","value":"true"}]}},{"type":"string","value":"\n"},{"type":"string","value":"[inMemory_blog]: "},{"type":"object","subtype":"array","className":"Array","description":"Array(2)","objectId":"{\"injectedScriptId\":1,\"id\":6}","preview":{"type":"object","subtype":"array","description":"Array(2)","overflow":false,"properties":[{"name":"0","type":"string","value":"id=[15034...];rev=[1-79c4b...]"},{"name":"1","type":"string","value":"id=[15034...];rev=[1-e9db6...]"}]}},{"type":"string","value":"\n"},{"type":"string","value":"[cached_blog]: "},{"type":"object","subtype":"array","className":"Array","description":"Array(2)","objectId":"{\"injectedScriptId\":1,\"id\":7}","preview":{"type":"object","subtype":"array","description":"Array(2)","overflow":false,"properties":[{"name":"0","type":"string","value":"id=[15034...];rev=[1-79c4b...]"},{"name":"1","type":"string","value":"id=[15034...];rev=[1-e9db[...]
To client: {"seq":0,"type":"event","event":"output","body":{"category":"stdout","output":"output","variablesReference":100007}}
From client: variables({"variablesReference":100007})
To client: {"seq":0,"type":"response","request_seq":9,"command":"variables","success":true,"body":{"variables":[{"name":"0","value":"Syncing [inMemory_blog] <-> [cached_blog]","variablesReference":0,"evaluateName":"0"},{"name":"1","value":"Sync {canceled: false, push: Replication, pull: Replication, pushPaused: true, pullPaused: true, …}","type":"Object","variablesReference":100008,"evaluateName":"1"},{"name":"2","value":"\n","variablesReference":0,"evaluateName":"2"},{"name":"3","value":"[inMemory_blog]: ","variablesReference":0,"evaluateName":"3"},{"name":"4","value":"Array(2) [\"id=[15034...];rev=[1-79c4b...]\", \"id=[15034...];rev=[1-e9db6...]\"]","type":"Object","variablesReference":100009,"indexedVariables":2,"namedVariables":2,"evaluateName":"4"},{"name":"5","value":"\n","variablesReference":0,"evaluateName":"5"},{"name":"6","value":"[cached_blog]: ","variablesReference":0,"evaluateName":"6"},{"name":"7","value":"Array(2) [\"id=[15034...];rev=[1-79c4b...]\", \"id=[15034...];rev=[1-e9db6...]\"]","type":"Object","variablesReference":100010,"indexedVariables":2,"namedVariables":2,"evaluateName":"7"}]}}

null: Syncing [inMemory_blog] <-> [cached_blog]
null: Sync {canceled: false, push: Replication, pull: Replication, pushPaused: true, pullPaused: true, …}
null: 

null: [inMemory_blog]: 
null: Array(2) ["id=[15034...];rev=[1-79c4b...]", "id=[15034...];rev=[1-e9db6...]"]
null: 

null: [cached_blog]: 
null: Array(2) ["id=[15034...];rev=[1-79c4b...]", "id=[15034...];rev=[1-e9db6...]"]
From client: setBreakpoints({"source":{"path":"c:\\Users\\sladj\\repos\\sam-cerebral\\src\\blog\\control\\actions.js","name":"actions.js"},"lines":[23],"breakpoints":[{"line":23}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":10,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":23,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000}]}}
From client: setBreakpoints({"source":{"path":"c:\\Users\\sladj\\repos\\sam-cerebral\\src\\blog\\control\\actions.js","name":"actions.js"},"lines":[],"breakpoints":[],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":11,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}
From client: setBreakpoints({"source":{"path":"c:\\Users\\sladj\\repos\\sam-cerebral\\src\\blog\\control\\actions.js","name":"actions.js"},"lines":[22],"breakpoints":[{"line":22}],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":12,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":22,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1001}]}}
From client: setBreakpoints({"source":{"path":"c:\\Users\\sladj\\repos\\sam-cerebral\\src\\blog\\control\\actions.js","name":"actions.js"},"lines":[],"breakpoints":[],"sourceModified":false})
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"setBreakpointsRequest","data":{"fileExt":".js"}}}
To client: {"seq":0,"type":"response","request_seq":13,"command":"setBreakpoints","success":true,"body":{"breakpoints":[]}}
From client: disconnect({"restart":false})
Terminated: Got disconnect request
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"debugStopped","data":{"reason":"Got disconnect request"}}}
To client: {"seq":0,"type":"event","event":"terminated"}
Killing Chrome process by pid: taskkill /F /T /PID 18712
To client: {"seq":0,"type":"response","request_seq":14,"command":"disconnect","success":true}
```

**Comment by roblourens** [comment] 2017-08-23 16:41
It says that inlined **sources** are ignored. Inlined sourcemaps are just fine. I can't tell what the problem is from the log - I see that node_modules in bundle.js were resolved in `c:\\Users\\sladj\\repos\\sam-cerebral\\static\\dist\\node_modules\\browser-pack\\_prelude.js` which looks correct but the rest of that line is cut off.

I recommend using the `.scripts` command to troubleshoot this, see the section on that in the readme.

**Closed** 2017-09-01 21:16 UTC
