### ISSUE TITLE
Extension stuck on updating

### ISSUE THREAD

**Issue by hypomicro** [Microsoft/vscode-chrome-debug#658] opened 2018-05-05 13:12 UTC
Debugger for Chrome seems to be stuck Installing. It begins updating after I launch VS Code and never stops. The installed version of the extension however seems to be working ok and I can use it as before. 

![2018-05-05 14_53_59-extension_ debugger for chrome - untitled workspace - visual studio code](https://user-images.githubusercontent.com/23087103/39663568-cae9dc32-5075-11e8-9eb1-554e0a0f5729.png)

- VS Code Version: 1.23.0

Steps to reproduce:
1. Open VS Code

**Comment by pkeuter** [comment] 2018-05-05 14:12
I guess this is a duplicate of #657

**Comment by MonstroMart** [comment] 2018-05-05 17:46
Yep can't install the new version. I uninstalled my old version to see if something was corrupted and now i'm stuck without any version since i can't re-install the new version. I even tried to install it manually with the VSIX and it's not working either.

**Comment by SmithCastro** [comment] 2018-05-05 20:58
I'm having the same issues as everyone else. Does anyone have a link to a previous version that doesn't get stuck in the "installing" limbo hell? I would like to install manually from the VSIX.

**Comment by roblourens** [comment] 2018-05-06 01:05
Sorry about this - 4.4.3 should work, please try it.

**Closed by roblourens** 2018-05-06 01:05 UTC

**Comment by MonstroMart** [comment] 2018-05-06 15:34
4.4.3 update worked for me ty.
