### ISSUE TITLE
Can't peek object properties after April update

### ISSUE THREAD

**Issue by BartoszBaczek** [Microsoft/vscode-chrome-debug#399] opened 2017-04-06 08:00 UTC
**VS Code Version:**
Version 1.11.0

**Steps to reproduce:**
1. Put breakpoint anywhere in your code
2. Hover mouse cursor over variable, which properties you want to peek

Before update I could see properties of object. Now I can see only short snippet of object.

![variable peeking](https://cloud.githubusercontent.com/assets/11254976/24743929/70048c96-1ab0-11e7-919a-c95d92003216.png)

**Comment by roblourens** [comment] 2017-04-06 15:07
Same root cause as https://github.com/Microsoft/vscode-chrome-debug-core/issues/195

**Comment by roblourens** [comment] 2017-04-06 16:59
Fixed in 2.7.3

**Closed by roblourens** 2017-04-06 16:59 UTC
