### ISSUE TITLE
Chome crashes when inpecting element with debugger attached

### ISSUE THREAD

**Issue by spectacularbob** [Microsoft/vscode-chrome-debug#372] opened 2017-02-24 20:48 UTC
Here is the contents of my launch.json:
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:3000",
            "webRoot": "${workspaceRoot}/app"
        }
    ]
}

Chrome Version 56.0.2924.87 (64-bit)

Steps to reproduce:

1. With no chrome.exe processes running:
2. Start debugging a javascript project, no need to be stopped on a breakpoint 
3. Right click anywhere on page in chrome and click inspect
4. Chrome crashes

**Comment by auchenberg** [comment] 2017-02-24 21:43
This is caused by Chrome DevTools taking over the connection to the debugger, and therefore closing the connection to VS Code.

Duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/116

**Closed by auchenberg** 2017-02-24 21:43 UTC
