### ISSUE TITLE
Not able to see values while inspecting on breakpoint (version 2.7.1)

### ISSUE THREAD

**Issue by prudvihemanth** [Microsoft/vscode-chrome-debug#394] opened 2017-04-03 10:38 UTC
Im developing Angular App with VSCode (1.10.1) and Chrome Debugger (2.7.1).

When setting a breakpoint and inspecting variables with mouseover I can only see values from local variables. Global or Closure variables don't open an inspector popup. Those values can be seen in "variables" window though. Can you please help me out..!

**Comment by simo3o** [comment] 2017-04-03 17:00
I'm having the same issue with 2.7.1 and 1.10.2 version of VSCode

**Comment by roblourens** [comment] 2017-04-03 21:14
Can you give me a code example where this happens?

**Comment by jschmidt42** [comment] 2017-04-05 14:30
I am also getting this issue, where hovering over variables does nothing and if I evaluate them in the debug console I get:

```
property
Cannot read property 'length' of undefined
Error processing "completions": TypeError: Cannot read property 'length' of undefined
    at trimProperty (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:167:18)
    at propertyPreviewToString (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:161:19)
    at props.map.prop (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:43)
    at Array.map (native)
    at getObjectPreview (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:151:14)
    at Object.getRemoteObjectPreview (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\variables.js:194:17)
    at ChromeDebugAdapter.createObjectVariable (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1540:33)
    at ChromeDebugAdapter.remoteObjectToVariable (C:\Users\jschmidt\.vscode\extensions\msjsdiag.debugger-for-chrome-2.7.2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1483:33)
    at ChromeDebugAdapter.internalPropertyDescriptorToVariable (C:\Users\jschmidt\.vscode\extensions\msjsdiag[...]
```

**Comment by roblourens** [comment] 2017-04-05 14:35
Can I see a code example? It works for me.

**Comment by jschmidt42** [comment] 2017-04-05 14:49
I noticed that when the Local scope doesn't show anything it is because some of the variables where constructed using `Object.defineProperty`, to behave like proxy objects. Here's the function that is used to construct these objects:

```
addProperty: function (obj, name, onGet, onSet, notEnumerable) {

    var
        oldValue = obj[name],
        getFn = function () {
            return onGet.apply(obj, [name, oldValue]);
        },
        setFn = function (newValue) {
            oldValue = onSet.apply(obj, [name, newValue]);
            return oldValue;
        };

    // Modern browsers, IE9+, and IE8 (must be a DOM object),
    if (Object.defineProperty) {

        Object.defineProperty(obj, name, {
            get: getFn,
            set: setFn,
            enumerable: !notEnumerable,
            configurable: true
        });

        // Older Mozilla
    } else if (obj.__defineGetter__) {
        obj.__defineGetter__(name, getFn);
        obj.__defineSetter__(name, setFn);
    } else {
        throw new Error('Browser not supported');
    }
},
```

And here's the snippet in which I noticed that Local variables and hovering wasn't working anymore:

![image](https://cloud.githubusercontent.com/assets/4054655/24711289/7d124630-19ed-11e7-8583-1df2ce513687.png)

As you can see `property` is not `undefined` because it was able to step in the `if` branch.

**Comment by roblourens** [comment] 2017-04-05 18:38
The errors you're seeing probably have the same root cause as https://github.com/microsoft/vscode-chrome-debug-core/issues/195. That could be behind variables missing from the variables pane (and missing hovers) as well.

I think there's a separate issue where a hover won't work when hovering over something outside of the current closure, when that hovered line isn't in a scope in the current callstack. It's by design in vscode but I can see how it would be annoying. Chrome devtools doesn't have that restriction and the tradeoff is that you can see incorrect hovers, like if you have a variable `foo` in the current function and an unrelated variable `foo` in another scope.

**Comment by simo3o** [comment] 2017-04-07 08:05
I've fixed my problem changing my gulpfile to not use babel, it looks that it doesn't work with it.

**Comment by roblourens** [comment] 2017-04-13 01:03
Closing per https://github.com/Microsoft/vscode-chrome-debug/issues/394#issuecomment-291955698

**Closed by roblourens** 2017-04-13 01:03 UTC
