### ISSUE TITLE
Support colors in debug console

### ISSUE THREAD

**Issue by morland96** [Microsoft/vscode-chrome-debug#537] opened 2017-11-05 09:04 UTC
`console.log("%c` Hello","color: #bada55")`
will show as:

`undefined
Hello`
hope it can support color. (I know it's difficult because actully is CSS)

**Comment by roblourens** [comment] 2017-11-05 16:31
Would need vscode support, there's no plan for this currently.

**Comment by aulisius** [comment] 2018-03-14 11:12
I'm really interested in this feature. What support would VSCode have to add in order for this to work? I would be happy to contribute if this feature can be made a reality.

**Comment by roblourens** [comment] 2018-06-06 17:14
Dupe of #282 (and vscode does support this)

**Closed by roblourens** 2018-06-06 17:14 UTC
Labels: enhancement
