### ISSUE TITLE
Support debugging Chrome extensions

### ISSUE THREAD

**Issue by PD75** [Microsoft/vscode-chrome-debug#155] opened 2016-04-22 08:53 UTC
I can not get it to work in chrome extensions. I created an error message and it shows up, but it seems it can not resolve the file paths.

```
ReferenceError: activate2 is not defined
    at new LayoutCtrl (chrome-extension://efdgnclniinhcpepdkeancnlobojadfb/app/core/layout/layout.js:18:5)
    at Object.invoke (chrome-extension://efdgnclniinhcpepdkeancnlobojadfb/dist/angular.js:4625:19)
   ...
```

If I click the file I get: `Unable to open 'layout.js': File not found (\\efdgnclniinhcpepdkeancnlobojadfb\app\core\layout\layout.js).`

I have the following configuration:

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}/appdev"
        }
    ]
}
```

**Comment by roblourens** [comment] 2016-04-22 23:15
That won't work yet. I'll tag it to work on

**Comment by Rev68** [comment] 2016-07-31 01:03
+1, this would be so useful! The ability to debug my extension across multiple web sites would be a dream come true

**Comment by Deniskore** [comment] 2016-08-29 19:42
+1 We need this feature!

**Comment by ArthurMenezes** [comment] 2017-12-07 21:54
Is this feature already working?

**Comment by vsDizzy** [comment] 2018-02-25 08:31
+1

**Comment by Morikko** [comment] 2018-05-12 20:05
It would be good !

**Comment by roblourens** [comment] 2018-05-14 04:38
This is probably possible with the right webRoot. I'm not going to work on this anytime soon but a PR would be welcome.

**Comment by vsDizzy** [comment] 2018-05-14 14:17
As is see the problem is that debugger attaching to first target from [http://127.0.0.1:9222/json/list](http://127.0.0.1:9222/json/list). @roblourens, can you give the directions?

**Comment by roblourens** [comment] 2018-05-14 16:17
There's no way to do that right now. There was a PR to support that kind of thing which was merged then reverted. There are some notes about how to implement it in here: https://github.com/Microsoft/vscode-chrome-debug/pull/623

**Closed** 2018-09-14 22:43 UTC
Labels: enhancement, out-of-scope
