### ISSUE TITLE
Display issue with multiple monitors (different resolution)

### ISSUE THREAD

**Issue by MettTheFrameless** [Microsoft/vscode-chrome-debug#575] opened 2018-01-05 04:24 UTC
- VS Code Version: 1.19.1
- OS: Win10

Steps to reproduce:

1. Close an instance of Chrome that is displayed on the WQHD monitor.
2. Run an instance of VSCode on another monitor that offers a FHD resolution.
3. Within this window you have to launch chrome.

Further information:
- If you drag this window to the smaller monitor it works.
- Within Windows' display settings I set the "Change the size of texts, apps and other items" to 125% but.

launch.json (default):
```
"version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "url": "http://localhost:8080",
            "webRoot": "${workspaceFolder}"
        }
    ]

```
![image](https://user-images.githubusercontent.com/33100708/34595276-fc392778-f1d6-11e7-96b1-d87952e98856.png)

EDIT:
![image](https://user-images.githubusercontent.com/33100708/34595719-5fbef8f6-f1da-11e7-9fde-5d90a5b687b7.png)

**Comment by roblourens** [comment] 2018-01-05 06:12
Sorry, I don't understand what the problem is? Can you explain some more?

**Comment by MettTheFrameless** [comment] 2018-01-05 06:34
Thank you for your response.

I have got to different Monitors (left: WQHD, right: FHD).
If I launch Chrome from VSCodes debugtab left window of the first picture shows up.
As you can see in the second picture the Chrometab overlaps.
In addition to that the 3/4th of the picture are black (picture one left window).

If i drag this window to the right (on the fhd monitor) it seems to work.

left monitor:
![image](https://user-images.githubusercontent.com/33100708/34598016-9b89574a-f1ea-11e7-970e-f18367b6dcff.png)

right monitor:
![image](https://user-images.githubusercontent.com/33100708/34598031-ae49d2c4-f1ea-11e7-9984-296df982c423.png)

I hope this clarifies the problem a bit.

**Comment by roblourens** [comment] 2018-01-05 15:44
Ok. I don't have any control over which window vscode opens on, so I don't think I can improve this, unless you have a suggestion. If you want to keep chrome open on the correct monitor, you could launch it in debug mode and use an "attach" config.

**Comment by MettTheFrameless** [comment] 2018-01-05 15:53
As far as I know a programs window will opened in the exact same location and ratio as it was closed in.

And as this seems to be a rather rare problem I guess Im going to stick with the attach solution.

**Comment by roblourens** [comment] 2018-01-05 15:54
If you don't have any other Chrome instances open, you could try running with `"userDataDir": false` to see if that improves things?

**Comment by MettTheFrameless** [comment] 2018-01-06 10:03
It opens Chrome (I closed it on the WQHD monitor before) and it has the same weird bug as before.

![image](https://user-images.githubusercontent.com/33100708/34638587-fb1e5d42-f2ce-11e7-93ef-95fc648f459f.png)


In addition to that I just dragged the visualstudiocode instance to the bigger bigger monitor and I guess its general VSCode bug ...
![image](https://user-images.githubusercontent.com/33100708/34638672-33ccbd94-f2d1-11e7-96d5-b481d8a46afd.png)

**Comment by roblourens** [comment] 2018-01-06 17:34
That might imply that it's a general Chrome bug (via electron for vscode). You could open an issue in the vscode repo for that to see if anyone knows anything about it.

I'm going to close this, as I don't think we can control this, unless you have any suggestions.

**Closed by roblourens** 2018-01-06 17:34 UTC

**Comment by MettTheFrameless** [comment] 2018-01-06 17:53
Thank you help so far.

I am going to open an issue over there.
