### ISSUE TITLE
Unable to use Chrome debug 

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode-chrome-debug#262] opened 2016-10-22 05:14 UTC
I must refresh once or Sometimes I need a break.
version 1.2.2

**Comment by roblourens** [comment] 2016-10-22 05:34
I just released v2, can you upgrade and try it?

**Comment by ydcoming** [comment] 2016-10-22 05:55
hello  I have just updated the version 2 but the worse, the contents of the debugging console without output。the code like this  in main.js


setTimeout(function () {
	alert("Asdas");
	var t = 100;
	console.log(t)
}, 5000);
window.onclick = function () {
	var t = 100;
	console.log(t)
}
function ko(params) {

}

**Comment by ydcoming** [comment] 2016-10-22 05:56
the vscode version is v1.6

**Comment by ydcoming** [comment] 2016-10-22 06:00
@roblourens  
![cj0awpj4 f8imy1pdodwvfv](https://cloud.githubusercontent.com/assets/3353702/19617313/d40bcd04-985f-11e6-9914-2a838bde8de2.png)

**Comment by auchenberg** [comment] 2016-10-22 16:39
@ydcoming 

How is `main.js` included on your page? Via a `<script>` tag in index.html? Can you share your `launch.json` config?

**Comment by ydcoming** [comment] 2016-10-24 02:31
main.js is included ,a <script> tag in index.html
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "${workspaceRoot}\\bin\\index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
             "port": 9222
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

**Comment by ydcoming** [comment] 2016-10-24 02:33
main.js included and it is a<script> tag in index.html
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "${workspaceRoot}\\bin\\index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
             "port": 9222
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

**Comment by ydcoming** [comment] 2016-10-24 02:33
main.js included and it is a<script> tag in index.html

**Comment by ydcoming** [comment] 2016-10-24 02:34
a <script> tag in index.html

**Comment by ydcoming** [comment] 2016-10-24 02:35
a script tag in index.html

**Comment by ydcoming** [comment] 2016-10-24 02:35
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Chrome against localhost, with sourcemaps",
            "type": "chrome",
            "request": "launch",
            "url": "${workspaceRoot}\\bin\\index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}",
             "port": 9222
        },
        {
            "name": "Attach to Chrome, with sourcemaps",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

**Comment by roblourens** [comment] 2016-10-24 02:38
Can you set 'diagnosticLogging' to look for clues? And upload the full log file from the path specified if you can't figure it out?

**Comment by ydcoming** [comment] 2016-10-24 07:39
Verbose logs are written to C:\Users\wangzhihua\.vscode\extensions\msjsdiag.debugger-for-chrome-2.0.0\vscode-chrome-debug.txt
下午3:38:57, 2016/10/24
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.2.0
debugger-for-chrome: 2.0.0
From client: initialize({"adapterID":"chrome","pathFormat":"path","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsVariablePaging":true,"supportsRunInTerminalRequest":true})
To client: {"seq":0,"type":"response","request_seq":1,"command":"initialize","success":true,"body":{"exceptionBreakpointFilters":[{"label":"All Exceptions","filter":"all","default":false},{"label":"Uncaught Exceptions","filter":"uncaught","default":true}],"supportsConfigurationDoneRequest":true,"supportsSetVariable":true,"supportsConditionalBreakpoints":true,"supportsCompletionsRequest":true}}
From client: launch({"name":"Launch Chrome against localhost, with sourcemaps","type":"chrome","url":"http://10.10.20.34:8000/index.html","runtimeExecutable":"C:/Program Files (x86)/Google/Chrome/Application/chrome.exe","runtimeArgs":["--allow-file-access-from-files","--allow-file-access-frome-files"," --disable-web-security"],"sourceMaps":true,"webRoot":"d:\\Documents\\myLayaaaasdaadaaaadasdasdfaaa","diagnosticLogging":true})
spawn('C:/Program Files (x86)/Google/Chrome/Application/chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--allow-file-access-from-files","--allow-file-access-frome-files"," --disable-web-security","http://10.10.20.34:8000/index.html"])
Discovering targets via http://127.0.0.1:9222/json
Attaching to target: {"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=127.0.0.1:9222/devtools/page/98DD99C0-5D0A-48E5-BA05-C916A1F7BB35","id":"98DD99C0-5D0A-48E5-BA05-C916A1F7BB35","title":"","type":"page","url":"http://10.10.20.34:8000/index.html","webSocketDebuggerUrl":"ws://127.0.0.1:9222/devtools/page/98DD99C0-5D0A-48E5-BA05-C916A1F7BB35"}
WebSocket Url: ws://127.0.0.1:9222/devtools/page/98DD99C0-5D0A-48E5-BA05-C916A1F7BB35
To target: "{\"id\":1,\"method\":\"Debugger.enable\"}"
To target: "{\"id\":2,\"method\":\"Runtime.enable\"}"
To target: "{\"id\":3,\"method\":\"Runtime.runIfWaitingForDebugger\"}"
To target: "{\"id\":4,\"method\":\"Runtime.run\"}"
From target: {"id":1,"result":{}}
From target: {"id":2,"result":{}}
From target: {"error":{"code":-32601,"message":"'Runtime.runIfWaitingForDebugger' wasn't found"},"id":3}
To client: {"seq":0,"type":"event","event":"initialized"}
To target: "{\"id\":5,\"method\":\"Runtime.evaluate\",\"params\":{\"expression\":\"navigator.userAgent\",\"silent\":true}}"
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
From target: {"id":4,"result":{}}
From client: setBreakpoints({"source":{"path":"d:\\Documents\\myLayaaaasdaadaaaadasdasdfaaa\\bin\\main.js","name":"main.js"},"lines":[6,2],"breakpoints":[{"line":6},{"line":2}],"sourceModified":false})
To client: {"seq":0,"type":"response","request_seq":3,"command":"setBreakpoints","success":true,"body":{"breakpoints":[{"verified":false,"line":6,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1000},{"verified":false,"line":2,"message":"Breakpoint ignored because generated code not found (source map problem?).","id":1001}]}}
From client: setExceptionBreakpoints({"filters":["uncaught"]})
To target: "{\"id\":6,\"method\":\"Debugger.setPauseOnExceptions\",\"params\":{\"state\":\"uncaught\"}}"
From target: {"method":"Debugger.globalObjectCleared","params":{}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"41","url":"","startLine":0,"startColumn":0,"endLine":319,"endColumn":84,"executionContextId":1,"isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"http://10.10.20.34:8000","name":"","frameId":"5236.2"}}}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"46","url":"","startLine":0,"startColumn":0,"endLine":0,"endColumn":19,"executionContextId":1,"isContentScript":false,"isInternalScript":true,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
From target: {"id":5,"result":{"result":{"type":"string","value":"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"},"wasThrown":false}}
Target userAgent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
From target: {"id":6,"result":{}}
To client: {"seq":0,"type":"response","request_seq":4,"command":"setExceptionBreakpoints","success":true}
From client: configurationDone(undefined)
To client: {"seq":0,"type":"response","request_seq":5,"command":"configurationDone","success":true}
From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"47","url":"http://10.10.20.34:8000/main.js","startLine":0,"startColumn":0,"endLine":12,"endColumn":0,"executionContextId":1,"isContentScript":false,"isInternalScript":false,"isLiveEdit":false,"sourceMapURL":"","hasSourceURL":false,"deprecatedCommentWasUsed":false}}
Paths.scriptParsed: could not resolve http://10.10.20.34:8000/main.js to a file under webRoot: d:\Documents\myLayaaaasdaadaaaadasdasdfaaa. It may be external or served directly from the server's memory (and that's OK).
From target: {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"type":"Extension","origin":"chrome-extension://memcfmlhlfmhbclbfkjbhdplilockfab","name":"Wwei\u4E8C\u7EF4\u7801\u751F\u6210\u5668","frameId":"5236.2"}}}

**Comment by roblourens** [comment] 2016-10-24 15:23
The problem is that main.js is actually at `bin\main.js`, and is served as `/main.js`, but your webRoot doesn't go down to `/bin`. It should work if you set `"webRoot":"d:\Documents\myLayaaaasdaadaaaadasdasdfaaa\bin"`.

You also mentioned that there's no output in the console. You're using Chrome v50. I can't guarantee something that old will be supported. Can you update Chrome? This is also in #265

**Comment by ydcoming** [comment] 2016-10-25 02:52
it works when i update the chrome but i need delay  for a while。for example：
function aa(){}
aa()
it does not work .
the second if url": "${workspaceRoot}\\bin\\index.html",like this  it not work .file:File Protocol？
if net Protocol it works。

**Comment by auchenberg** [comment] 2016-10-25 03:41
Seems to be a duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/264, as the issue only happens when using `file://`

**Comment by roblourens** [comment] 2016-10-25 04:37
@ydcoming When you say you need to delay for awhile, I assume you are seeing that if you have a breakpoint on code that runs immediately, it won't be hit. That's expected- the code will run before the debugger attaches.

And yeah, bps in `file:///` URLs won't work right now.

**Closed** 2016-10-25 04:37 UTC
