### ISSUE TITLE
Can't find a page with url, available pages...

### ISSUE THREAD

**Issue by wangbourne** [Microsoft/vscode-chrome-debug#160] opened 2016-05-20 11:43 UTC
I think I have configured correctly:

{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch index.html",
            "type": "chrome",
            "request": "launch",
            "file": "${workspaceRoot}/index.html",
            "sourceMaps": true,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

but visual studio code gives following error:

›Warning: Can't find a page with url: /users/bourne/desktop/test/index.html. Available pages: ["file:///Users/bourne/Desktop/test/index.html"]

**Comment by auchenberg** [comment] 2016-05-21 20:46
@roblourens Is this related to the casing sensitive comparison or because the of the `file://` prefix?

**Comment by roblourens** [comment] 2016-05-23 16:35
This is because of the case-sensitive comparison (workspaceRoot clobbers the actual casing) but even if you see that warning, it should still attach to the page. That's just to filter out the expected page from other tabs. Does it fail after this? Can I see the rest of the logs?

**Comment by wangbourne** [comment] 2016-05-23 19:49
hi roblourens
that's the only logs I can get, and yes, it still attach to the page :)

**Comment by auchenberg** [comment] 2016-05-24 09:49
Closing as duplicate of https://github.com/Microsoft/vscode-chrome-debug/issues/156

**Closed by auchenberg** 2016-05-24 09:49 UTC
Labels: duplicate
