### ISSUE TITLE
Crash in this sourcemap path case. 'path must be a string'

### ISSUE THREAD

**Issue by Mimetis** [Microsoft/vscode-chrome-debug#268] opened 2016-10-25 18:22 UTC
Since version 2.0.0, I can't debug a straightforward sample with :
Angular CLI 
Angular Material

Without Angular Material, it works fine.
The problem comes from the hammer.min.js file included in the script array, in the Angular CLI config file.

Here is my launch json file config :

```
    {
        "name": "Launch Chrome for webpack",
        "type": "chrome",
        "request": "launch",
        "url": "http://localhost:4200/",
        "sourceMaps": true,
        "webRoot": "${workspaceRoot}/src",
        "diagnosticLogging": true,
        "runtimeArgs": [
            "--disable-session-crashed-bubble",
            "--disable-infobars"
        ],
        "userDataDir": "c:\\temp\\chorme_out_dir",
        "sourceMapPathOverrides": {
            "webpack:///C:*": "C:/*"
        }
```

And here is the diagnostic :

```
SourceMaps.scriptParsed: http://localhost:4200/styles.bundle.js was just loaded and has mapped sources: ["c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\style-loader\\addStyles.js","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.svg","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.ttf","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.woff","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.woff2","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\css-loader\\lib\\css-base.js","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.eot","c:\\PROJECTS\\ANGULAR2\\ngcli04\\src\\styles.css","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\@angular\\material\\core\\theming\\prebuilt\\deeppurple-amber.css","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\css\\bootstrap-theme.min.css","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\bootstrap\\dist\\css\\bootstrap.min.css","c:\\PROJECTS\\ANGULAR2\\ngcli04\\src\\styles.css"]
Paths.scriptParsed: could not resolve http://localhost:4200/scripts.bundle.js to a file under webRoot: c:\PROJECTS\ANGULAR2\ngcli04/src. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/scripts.bundle.js by URI: scripts.map and webRoot: c:\PROJECTS\ANGULAR2\ngcli04/src
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/scripts.map
SourceMap: creating for http://localhost:4200/scripts.bundle.js
SourceMap: sourceRoot: 
SourceMap: sources: ["webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/script-loader/addScript.js","webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/hammerjs/hammer.min.js?744b","webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/hammerjs/hammer.min.js"]
SourceMap: webRoot: c:\PROJECTS\ANGULAR2\ngcli04/src
SourceMap: no sourceRoot specified, using webRoot + script path dirname: c:\PROJECTS\ANGULAR2\ngcli04\src\
SourceMap: mapping webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/script-loader/addScript.js => C:\PROJECTS\ANGULAR2\ngcli04\~\script-loader\addScript.js, via sourceMapPathOverrides entry - "webpack:///C:*": "C:/*"
SourceMap: mapping webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/hammerjs/hammer.min.js?744b => C:\PROJECTS\ANGULAR2\ngcli04\~\hammerjs\hammer.min.js?744b, via sourceMapPathOverrides entry - "webpack:///C:*": "C:/*"
SourceMap: mapping webpack:///C:/PROJECTS/ANGULAR2/ngcli04/~/hammerjs/hammer.min.js => C:\PROJECTS\ANGULAR2\ngcli04\~\hammerjs\hammer.min.js, via sourceMapPathOverrides entry - "webpack:///C:*": "C:/*"
SourceMaps.scriptParsed: http://localhost:4200/scripts.bundle.js was just loaded and has mapped sources: ["c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\script-loader\\addScript.js","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\hammerjs\\hammer.min.js","c:\\PROJECTS\\ANGULAR2\\ngcli04\\~\\hammerjs\\hammer.min.js"]
SourceMaps.getMapForGeneratedPath: Finding SourceMap for debugadapter://39 by URI: hammer.min.js.map and webRoot: c:\PROJECTS\ANGULAR2\ngcli04/src

```

The problem appears to be this line in the cli config :

```
  "scripts": [
    "../node_modules/hammerjs/hammer.min.js" 
  ],
```

Once i removed it, it works correctly

```
  "scripts": [
  ],
```

**Comment by roblourens** [comment] 2016-10-25 18:27
What problem is that file causing exactly? The `~` isn't resolved to the node_modules path, but that's ok assuming you aren't trying to set breakpoints in it.

**Comment by Mimetis** [comment] 2016-10-26 09:19
I dont know what is the exact problem, to be honest.
The only thing i see is with any file in the scripts array, it doesn't work.
Do you recreate the problem ? (juste create a simple CLI project with angular material)

**Comment by roblourens** [comment] 2016-10-26 16:18
Can you tell me exactly what the problem is? What is, "it doesn't work".

**Comment by Mimetis** [comment] 2016-10-27 08:51
The problem is : The debug adapter process has terminated unexpectedly :


![errorvschromedebug](https://cloud.githubusercontent.com/assets/4592555/19760646/ee54f1be-9c32-11e6-9ffd-4657af787f53.PNG)

Without the script in the scripts[] array config, it works as expected :

![errorvschromedebug2](https://cloud.githubusercontent.com/assets/4592555/19760740/521965f4-9c33-11e6-8c54-7e5ad1861428.PNG)

**Comment by roblourens** [comment] 2016-10-27 15:33
Ok, that's definitely a problem. Can you post the full log, from the path that's printed at the top of the debug console? Or, open Help > Developer tools, and look for errors in the console?

**Comment by roblourens** [comment] 2016-11-01 23:37
I'm just going to guess that this was the same as #274, which should be fixed in 2.1.3. Please let me know if you keep seeing it.

**Comment by tomwanzek** [comment] 2016-11-07 20:16
@Mimetis Have you been able to get this issue resolved? I am experiencing the same issue with VS Chrome Debug 2.2.1 on an angular-cli 1.0.0-beta.19-3 with angular material 2 (alpha.9-3).

Same behavior as you described, in that getting the source map for `hammer.min.js` lets the debugger terminate unexpectedly. If I remove the script from the `scripts` in `angular-cli.json` the debugging works, but the app  will throw an  error when it hits the material slide toggle which uses hammer.js

**Comment by roblourens** [comment] 2016-11-07 21:34
Does it log the error? I need more information.

**Comment by tomwanzek** [comment] 2016-11-07 23:42
The status bar error is `Debug adapter process has terminated unexpectedly`.

Steps to reproduce:
(1) Start the angular-cli development server with `ng serve`
(2) launch with `launch.json`:
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Launch Chrome against localhost, with sourcemaps",
      "type": "chrome",
      "request": "launch",
      "diagnosticLogging": true,
      "url": "http://localhost:4200/",
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",
      "sourceMapPathOverrides": {
        "webpack:///C:*": "c:/*"
      }
    },
    {
      "name": "Attach to Chrome, with sourcemaps",
      "type": "chrome",
      "request": "attach",
      "diagnosticLogging": true,
      "url": "http://localhost:4200/*",
      "port": 9222,
      "sourceMaps": true,
      "webRoot": "${workspaceRoot}",
      "sourceMapPathOverrides": {
        "webpack:///C:*": "c:/*"
      }
    }
  ]
}
```
The app launches in Chrome 

The verbose debug console output is:
```
Verbose logs are written to C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\vscode-chrome-debug.txt
6:28:07 PM, 2016-11-07
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.6.1
debugger-for-chrome: 2.2.0
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","http://localhost:4200/"])
Discovering targets via http://127.0.0.1:9222/json
Target userAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Paths.scriptParsed: could not resolve http://localhost:4200/inline.js to a file under webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/inline.js by URI: inline.map and webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/inline.map
SourceMap: creating for http://localhost:4200/inline.js
SourceMap: sourceRoot: 
SourceMap: sources: ["webpack:///webpack/bootstrap 741bc784c2e2d21c9504"]
SourceMap: webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME
SourceMap: no sourceRoot specified, using webRoot + script path dirname: c:\Users\USERNAME\vscode\PROJECT-NAME\
SourceMaps.scriptParsed: http://localhost:4200/inline.js was just loaded and has mapped sources: ["c:\\Users\\USERNAME\\vscode\\PROJECT-NAME\\webpack:\\webpack\\bootstrap 741bc784c2e2d21c9504"]
Paths.scriptParsed: could not resolve http://localhost:4200/styles.bundle.js to a file under webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/styles.bundle.js by URI: styles.map and webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/styles.map
Paths.scriptParsed: could not resolve http://localhost:4200/scripts.bundle.js to a file under webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME. It may be external or served directly from the server's memory (and that's OK).
SourceMaps.getMapForGeneratedPath: Finding SourceMap for http://localhost:4200/scripts.bundle.js by URI: scripts.map and webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME
SourceMaps.loadSourceMapContents: Downloading sourcemap file from http://localhost:4200/scripts.map
SourceMaps.getMapForGeneratedPath: Finding SourceMap for eval://53 by URI: hammer.min.js.map and webRoot: c:\Users\USERNAME\vscode\PROJECT-NAME
******** Unhandled error in debug adapter: TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at Object.resolveMapPath (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapUtils.js:106:96)
    at getSourceMapContent (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:71:30)
    at Object.getMapForGeneratedPath (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:29:30)
    at SourceMaps.processNewSourceMap (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMaps.js:63:32)
    at BaseSourceMapTransformer.scriptParsed (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\transformers\baseSourceMapTransformer.js:189:37)
    at ChromeDebugAdapter.onScriptParsed (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:314:56)
    at Client.chrome.Debugger.onScriptParsed.params (C:\Users\USERNAME\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:141:60)
   [...]
```

Hope this sheds some light on it...

**Comment by roblourens** [comment] 2016-11-08 00:00
Ahh I see the problem... thanks!

**Comment by tomwanzek** [comment] 2016-11-08 00:13
No worries. On a related note: What is the recommended approach to the `webRoot` config option when debugging angular-cli? In the `launch.json` I used, I simply used `"webRoot": "${workspaceRoot}"`.

I have seen other references using:  `"webRoot": "${workspaceRoot}/src"` (including the initial post here). My Clearly, the application source files are in the `/src` directory. `ng serve` compiles/webpacks and serves from memory so I'm not 100%.

At a minimum, I will note that on a Windows 10 machine using `${workspaceRoot}/src` will lead to a resolved path inadvertently using backward slashes within the workspace path and a forward slash for `/src`. So the viable alternative would be if anything `${workspaceRoot}\\src` . Penny for your thoughts...

**Comment by roblourens** [comment] 2016-11-08 00:32
I'm not sure it matters that much here. It's necessary when you have to resolve a url to a path on disk- it tells the extension where on disk the webserver's `/` is. But here, you have script bundles that don't exist on disk, and the sourcemap paths have the full path to sources.

I've seen other webpack configs that output sourcemaps with paths that are relative to the project. In that case, it would use one of the built-in 'sourceMapPathOverrides' which depend on webRoot, and it would have to be set correctly.

**Comment by tomwanzek** [comment] 2016-11-14 18:44
@roblourens Thanks for all the hard work on this extension! Is there an ETA for a fix to this bug?

**Comment by Successful** [comment] 2016-11-25 20:17
@roblourens Yes thanks for all work. 
I am also waiting for this fix and gladly helps out if you don't have the time.

**Closed** 2016-11-27 23:11 UTC
Labels: bug

**Comment by tomwanzek** [comment] 2016-11-27 23:19
Yey, looking forward to this! 🎉
