### ISSUE TITLE
Source maps containing sources are not supported (sourcesContent).

### ISSUE THREAD

**Issue by ffaubry** [Microsoft/vscode-chrome-debug#60] opened 2015-12-04 17:14 UTC
I must be completely missing something but I cannot get a the source map story and breakpoints...
I have a ES6 project that get transpiled into a directory:
./out
  index.html
  myApp.js
  myApp.map

When I use the dev tools directly under Chrome, everything works as expected, I get my source map correctly working. I can set break point etc.

Now I'm using this extension, with the following launch settings:
    {
      "name": "Launch Web App",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200/",
      "webRoot": "./out",
      "sourceMaps": true,
      "userDataDir": "./tmp"
    }

Chrome launch, my app launch, then what?!

I tried to set break point in myApp.js with no luck.
And is it really where breakpoint should be set?
Are we going to have a window that will show the code structure as define in the source map?

**Comment by roblourens** [comment] 2015-12-07 22:17
Sorry for the slow response @ffaubry - that config looks correct as far as I know. If sourcemaps work in Chrome dev tools, they should work with this extension too.

Does it work with sourcemaps disabled? Also I updated it yesterday so try installing the latest version if you haven't already. And if you share the log from a run with diagnosticLogging enabled, I can try to help you debug it. Sorry, I know this is frustrating, I'm still trying to make it easier.

**Comment by ffaubry** [comment] 2015-12-07 22:51
@roblourens Thanks for the reply. No worry, no frustration here. I'm still using the chrome devtools until this works for me. I would love to debug from inside VS Code. May be I don't understand what I'm suppose to see in VSCode!? When I debug my app under chrome devtools, I see a virtual source tree from the webroot:
![image](https://cloud.githubusercontent.com/assets/3506166/11642072/cee2a4e4-9cf0-11e5-9af7-165676e073d5.png)

I'm expecting the same UX in VS Code. 
This is my webroot:
![image](https://cloud.githubusercontent.com/assets/3506166/11642107/0da637b8-9cf1-11e5-9070-77d08aff5b26.png)

My expectations were that the source map would be used to show a virtual source code tree in which I could set my breakpoints, etc.
Am I supposed to see a new window?! How can I set my breakpoints.

Here is my log:
  ›From target: {"method":"Debugger.globalObjectCleared"}
  ›From target: {"id":2,"result":{}}
  ›To client: {"seq":0,"type":"event","event":"initialized"}
  ›To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":true}
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/app_electron/create-window.js"},"lines":[]})
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/app_electron/create-window.js can't be resolved to a loaded script.
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/app_electron/windows-manager.js"},"lines":[]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/app_electron/workflow-manager.js"},"lines":[]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/app_electron/portals-manager.js"},"lines":[]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/app_electron/portal.js"},"lines":[]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/node_modules/ember-cli/lib/tasks/serve.js"},"lines":[55,22]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/node_modules/ember-cli/lib/tasks/server/express-server.js"},"lines":[208,211,85]})
  ›From client: setBreakpoints({"source":{"path":"/Users/fred/Documents/WebProjects/nickel/web/assets/nickel.js"},"lines":[4553]})
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/app_electron/windows-manager.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/app_electron/workflow-manager.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/app_electron/portals-manager.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/app_electron/portal.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/node_modules/ember-cli/lib/tasks/serve.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/node_modules/ember-cli/lib/tasks/server/express-server.js can't be resolved to a loaded script.
  ›SourceMaps.setBP: /Users/fred/Documents/WebProjects/nickel/web/assets/nickel.js can't be resolved to a loaded script.
  ›From client: setExceptionBreakpoints({"filters":[]})
  ›To target: {"id":3,"method":"Debugger.setPauseOnExceptions","params":{"state":"none"}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"49","url":"http://fredmac2.esri.com:4200/ember-cli-live-reload.js","startLine":0,"startColumn":0,"endLine":6,"endColumn":5,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve http://fredmac2.esri.com:4200/ember-cli-live-reload.js to a file in the workspace. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"id":3,"result":{}}
  ›To client: {"seq":0,"type":"response","request_seq":11,"command":"setExceptionBreakpoints","success":true}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"50","url":"http://fredmac2.esri.com:49152/livereload.js?snipver=1","startLine":0,"startColumn":0,"endLine":1183,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: could not resolve http://fredmac2.esri.com:49152/livereload.js?snipver=1 to a file in the workspace. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"51","url":"http://fredmac2.esri.com:4200/assets/amd-config.js","startLine":0,"startColumn":0,"endLine":67,"endColumn":28,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/assets/amd-config.js to /Users/fred/Documents/WebProjects/nickel/web/assets/amd-config.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"52","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/dojo.js","startLine":0,"startColumn":0,"endLine":2026,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/dojo.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/dojo.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"53","url":"","startLine":0,"startColumn":0,"endLine":2,"endColumn":2}}
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"54","url":"http://fredmac2.esri.com:4200/assets/amd-start.js","startLine":0,"startColumn":0,"endLine":142,"endColumn":3,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/assets/amd-start.js to /Users/fred/Documents/WebProjects/nickel/web/assets/amd-start.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"55","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/Deferred.js","startLine":0,"startColumn":0,"endLine":320,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/Deferred.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/Deferred.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"56","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/Deferred.js","startLine":0,"startColumn":0,"endLine":383,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/Deferred.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/_base/Deferred.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"57","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/config.js","startLine":0,"startColumn":0,"endLine":197,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/config.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/_base/config.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"58","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/fx.js","startLine":0,"startColumn":0,"endLine":676,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/fx.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/_base/fx.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"59","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/lang.js","startLine":0,"startColumn":0,"endLine":616,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/lang.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/_base/lang.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"60","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/url.js","startLine":0,"startColumn":0,"endLine":109,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/_base/url.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/_base/url.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"61","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/cookie.js","startLine":0,"startColumn":0,"endLine":98,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/cookie.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/cookie.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"62","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/date/locale.js","startLine":0,"startColumn":0,"endLine":694,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/date/locale.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/date/locale.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"63","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/fx/easing.js","startLine":0,"startColumn":0,"endLine":276,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/fx/easing.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/fx/easing.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web
  ›From target: {"method":"Debugger.scriptParsed","params":{"scriptId":"64","url":"http://fredmac2.esri.com:4200/esri-js-api/dojo/has.js","startLine":0,"startColumn":0,"endLine":187,"endColumn":0,"sourceMapURL":""}}
  ›Paths.scriptParsed: resolved http://fredmac2.esri.com:4200/esri-js-api/dojo/has.js to /Users/fred/Documents/WebProjects/nickel/web/esri-js-api/dojo/has.js. webRoot: /Users/fred/Documents/WebProjects/nickel/web

**Comment by roblourens** [comment] 2015-12-08 06:28
So this is sort of the fundamental difference between sourcemap debugging with Chrome Dev Tools, and with this extension. CDT will find the sourcemap, download the source file from the site, and add it to the tree. But when the extension sees a script with a sourcemap, it will try to figure out which source file in your workspace it maps to. So you just need to open the source file in Code that's already on your computer and set your breakpoints there.

From the email you sent, I see that nickel.js and its map is loaded, and the extension is looking for its sources in a place like `.../nickel/web/assets/nickel/application/route.js`. Apparently that isn't right, looking at your file tree in the picture. Where's the actual location of your sources, and how are they downloaded by Chrome?

**Comment by ffaubry** [comment] 2015-12-08 19:04
@roblourens Ok good question... I dug in the nickel.map, here is the structure:
- version: 3
- sources: []
- sourcesContent: []
- names: []
- mappings: []

After reading about source map, it seems that the sources are included in the map in my scenario. The sourcesContent is a massive array with code...
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pli=1

This explains my confusion. 

I see two options:
a) we have to present a UX for being able to set breakpoints in the map included source (what chrome does). I see this as a big task... 
b) via the launch.json properties, I can somehow tell where the sources are...

(I will send the map file by email.)

**Comment by roblourens** [comment] 2015-12-10 06:30
Ah I see, that's right - the extension doesn't load sources from sourcesContent. This is by design - what I expect is that the typical user has Code open to the folder containing their sources already. Then they can edit and set breakpoints in the same file. It should work even if the built js files are not under the open directory, as long as webRoot is set correctly.

**Comment by ffaubry** [comment] 2015-12-10 19:25
@roblourens Let me give you some background. I'm using Ember-cli (http://ember-cli.com/) for my web development. My files are in ES6 under a folder called 'app'. It's also using files under bower_components. The Ember build system output everything into a directory called 'dist':
project:
  - app <- ES6 code
  - bower_modules
  - dist <- result of the build in ES5 with source map

This is why the source map contains the source code, because there is no way to map back form ES5 to ES6.

I think that if you want to support ES6 projects that get 'transpiled' into ES5 by Babel or other transpiler, you will have to support source code in source map...

At minimum, this is limitation that you should document in the README.md.

Thanks for you help. I really appreciated. I will continue to monitor your project in case you decide to support the scenario above.

**Comment by roblourens** [comment] 2015-12-10 20:40
There shouldn't be any problem with sourcemapping between ES5 and ES6. If sourcesContent is the same as the file on disk, then this should be workable. Are you saying that sourcesContent contains a different version of the code, like from an intermediate build step?

**Comment by roblourens** [comment] 2015-12-17 02:46
@ffaubry I'm going to close this - it should be possible to set up sourcemaps unless there's something I don't understand about your situation. In any case, for the scenario I'm trying to enable, it doesn't really make sense for this extension to look at sourcesContent.

**Closed by roblourens** 2015-12-17 02:46 UTC
