### ISSUE TITLE
Chrome version 69 get freezed after while working with it

### ISSUE THREAD

**Issue by blopez2010** [microsoft/vscode-chrome-debug#733] opened 2018-09-19 14:08 UTC
- VS Code Version: Version 1.27.2 (1.27.2)
- Log file (set `"trace": true` in launch config):
[vscode-chrome-debug.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2397339/vscode-chrome-debug.txt)

Task config:

```{
    "version": "2.0.0",
    "tasks": [
      {
        "identifier": "ng serve",
        "type": "npm",
        "script": "start",
        "problemMatcher": [],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      },
      {
        "identifier": "ng test",
        "type": "npm",
        "script": "test",
        "problemMatcher": [],
        "group": {
          "kind": "test",
          "isDefault": true
        }
      },
      {
        "type": "npm",
        "script": "test-debug",
        "problemMatcher": []
      }
    ]
  }
```

Launch config:

```{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "launch",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:4200/",
      "webRoot": "${workspaceRoot}",
      "userDataDir": "${workspaceRoot}/.vscode/chrome",
      "sourceMaps": true,
      "trace": true
    },
    {
      "name": "test",
      "type": "chrome",
      "request": "launch",
      "url": "http://localhost:9876/debug.html",
      "webRoot": "${workspaceRoot}",
      "sourceMaps": true
    },
    {
      "name": "ng e2e",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/protractor/bin/protractor",
      "protocol": "inspector",
      "args": ["${workspaceRoot}/protractor.conf.js"]
    }
  ]
}
```

Steps to reproduce:

1. Press cmd+shift+B to start default task
2. Press F5 to start debugging.
3. Play with the app and after a while (some minutes after like 5 min more or less) the chrome instance gets freezed.

Activity monitor capture:
![image](https://user-images.githubusercontent.com/15872584/45758517-06bfbf00-bbe3-11e8-96eb-2b4bd0d149a1.png)

**Comment by roblourens** [comment] 2018-09-21 17:49
Does this happen every time? I haven't seen it. I'm curious whether you've seen it with Chrome devtools at all?

**Comment by blopez2010** [comment] 2018-09-21 17:55
Yes, it does, I haven't tried with Chrome devtools since I use vscode debugger only.

**Comment by roblourens** [comment] 2018-09-21 17:59
Sorry, no idea. Maybe you can download Chrome Canary and see if it happens there too?

**Comment by blopez2010** [comment] 2018-09-21 22:34
Downloading and check what happens, I will let you know.

**Comment by abdurrahmanarikan** [comment] 2018-09-22 21:37
Same here, chrome starts up with safe mode (I think; because of vscode, since no extensions run on when code fires chrome up). It runs for 5-10 secs then chrome asks translate web page, boom! you have to stop your debugging and start the debugging again (at least for an angular project).

**Comment by roblourens** [comment] 2018-09-23 17:52
@abdurrahmanarikan can you check whether it happens with Chrome devtools?

And can either of you share your project, in case it's related to the project itself?

**Comment by blopez2010** [comment] 2018-09-24 13:34
I can't share my project, I've been testing with Chrome Canary and seems to be working. My project is an Angular 6 app too.

**Comment by abdurrahmanarikan** [comment] 2018-09-24 19:55
sorry, can't share It's a private repo. It happens independently from devtools...

**Comment by blopez2010** [comment] 2018-09-24 19:58
By far, I can confirm Google Canary has been the best solution to this problem, it might be the production version that could be broken somehow.

**Comment by roblourens** [comment] 2018-09-24 20:58
Cool, sounds like a fix is in the pipeline. I'll leave this open for a bit in case that doesn't totally fix it...

**Comment by blopez2010** [comment] 2018-09-25 13:30
Chrome Canary started to fail with same issue today 😞the project is in Angular with Material, so when I click an icon (`<mat-icon class="Icon--green">delete</mat-icon>`) or a button like:

```  
<a
     mat-raised-button
     class="add-timeline-event srlgx-icon"
     color="primary"
     onclick="return false;">
    <mat-icon></mat-icon>
  </a>
```
CSS:
```
.srlgx-icon {
  background-color: $main-color !important;
  padding: 0.3em 0.3em !important;
  width: 2.5em;
  height: 2em;
  &:hover {
    background-color: $icon-hover-color !important;
  }
}

.add-timeline-event {
    width: 3em;
    border-radius: 8px !important;
    height: 2em;
    padding: 0;
    padding-top: 0.4em;
    min-width: unset;
    .mat-icon {
      background-image: url(/assets/study-management/add-treatment-group.png);
      width: 1.5em;
    }
  }
```

**Package.json**
I had to change extension to `txt` because of gitlab uploading restrictions.
[package.json.txt](https://github.com/Microsoft/vscode-chrome-debug/files/2415395/package.json.txt)

**Comment by ougarte** [comment] 2018-10-31 02:52
I could reproduce same issue

Tech Details
macOS Mojave - Version 10.14
Debugger for Chrome - Version 4.10.2
Chrome - Version 70.0.3538.77 
VSCode - Version 1.28.2

index.html
```html
<!doctype >
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Training - Frontend Technologies</title>
	</head>
	<body>
		<button>click me</button>
	</body>
</html>
```
launch.json
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch index.html",
			"type": "chrome",
			"request": "launch",
			"file": "${workspaceFolder}/index.html"
	},
	]
}
```
Steps:
1. Start debugging, be sure that Chrome has been opened
2. Maximize Chrome
3. Click on button, at least 15 times or maybe more
4. Chrome gets freezed

I hope this help...

**Comment by connor4312** [comment] 2020-11-03 20:05
We've since moved a new debugger in VS Code -- if you're still having this issue there, please open an issue on [the new repo](https://github.com/microsoft/vscode-js-debug/).

**Closed by connor4312** 2020-11-03 20:05 UTC
Labels: needs more info
