### ISSUE TITLE
debug console unaware of "this" member when in class methods

### ISSUE THREAD

**Issue by nitrologic** [microsoft/vscode-chrome-debug#918] opened 2019-08-21 21:29 UTC
When using chrome plugin often I breakpoint and want to view "this" in Debug Console. The auto complete hates this and fights me in an annoying manner.

**Comment by nitrologic** [comment] 2019-08-24 20:02
To reproduce from DEBUG CONSOLE and type the letters t, h, i, s and then press Enter key.

comment - Instead of doing what it is told auto correct has intercepted the Enter key and informed me i must mean globalThis.

**Comment by roblourens** [comment] 2019-08-26 03:14
Hm, not sure when we lost this since it does show up in the variables list.

**Comment by Lazarencjusz** [comment] 2019-09-24 09:07
@roblourens it is present in `Variables` section, but the preview (I can see) always pointing to `Local` scope, when it is more relevant to point to the class scope:
![image](https://user-images.githubusercontent.com/6573466/65498062-8699fc80-debb-11e9-8047-938731c4620f.png)

Is it possible to overwrite `Local` scope?

**Comment by nitrologic** [comment] 2019-10-13 20:56
The behavior seems to have changed in 1.39.0. I can now type this and hit Enter as Debug Console input without being assaulted by autocomplete, however the word this is then printed in the Debug Console output and the debugger seems to die with the likes of:

`Error: Set breakpoints request timed out
    at Timeout.setTimeout [as _onTimeout] (c:\Users\Simon\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.0\node_modules\vscode-chrome-debug-core\out\src\utils.js:96:24)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)`

**Comment by connor4312** [comment] 2020-11-03 18:43
Functional duplicate of https://github.com/microsoft/vscode/issues/12066

**Closed by connor4312** 2020-11-03 18:43 UTC
